### ISSUE TITLE
[Episode 3] HP Attack+Drain oversight doesn't work correctly online

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#118]
First, here's how the oversight works:

(HP/AP)

- Have FC with 10/4
- Attack target with HP Attack, so it becomes 4/10
- Do 10 damage with Drain, healing the FC for 3, so it becomes 7/10
- The FC will then swap its values back as is, permanently becoming 10/7

This oversight works with FCs that have Drain natively by only playing HP Attack (e.g. Sange & Yasha), and it also works if the HP Attack and Drain cards is played on other weapons.

However, when online, linking HP Attack and Drain onto an FC does not permanently increase their AP after the swap and drain effect. Using a FC such as Sange & Yasha does though. I'm not entirely sure what happens if the FC has lost HP before the attack.

As usual, let me know if you need anything else.

**Comment by fuzziqersoftware** [comment]
This is fixed now. The bug was that I had made a copy-paste error in a function that checks for duplicate action cards, so it thought every action card in a chain after the first was a duplicate, and skipped applying effects for all of them except the first. This is why Sange & Yasha worked correctly - only one action card was needed to make this behavior work as it does offline, whereas most other weapons would require two. Drain has to be the last card in the chain since it has no right-side colors, so it was always the one whose effects were skipped.

I also noticed a curious behavior: this behavior doesn't work at all when attacking a Rag Rappy. Even offline, the attacking weapon gains no AP. I suspect this has something to do with Rag Rappy's Inherit effect, but haven't spent much time looking into it.
