### ISSUE TITLE
[Blue Burst] Incorrect Stats with Level Up command

### ISSUE THREAD

**Issue by Sazonde99** [fuzziqersoftware/newserv#119]
Started with 40HP/29TP on a HUmar at Lv1. A natural level up added these stats below. It properly reflects the stats on the menu as well.
![image](https://github.com/fuzziqersoftware/newserv/assets/123838641/e7e2025d-557e-4ece-b0a4-49626be44817)
![image](https://github.com/fuzziqersoftware/newserv/assets/123838641/98901560-2b5e-4466-b2c2-6478b6ba64bb)

Using $edit level 2, there is no change in your stats (even when set to as high as Lv200) except for HP/TP but as you can see below it's not correct either.
![image](https://github.com/fuzziqersoftware/newserv/assets/123838641/8998cc72-9417-4ea5-a505-7b2b3929b40d)

**Comment by nolrinale** [comment]
@fuzziqersoftware Since PSOBB cannot offer a menu in-game to defeat all enemies at once to verify their drops/rates,etc it would be a good idea to implement this change to quickly level up with the correct stats, get geared and be able to test the monster drops at different difficulties with the `$edit level` command.

**Comment by fuzziqersoftware** [comment]
This was already fixed in 724186a8.
