### ISSUE TITLE
[Episode 3] AP Silence temporarily cancels out simultaneous AP Growth effects

### ISSUE THREAD

**Issue by SparkeeLecaro** [fuzziqersoftware/newserv#122]
Noticed this on the server earlier this evening. A Govulmer (which has AP Silence as an ability) attacked a Belra Cannon (7 AP), and Grow Guard (permanent +1 AP after taking the hit) was played as a defense card. This resulted in Belra Cannon dropping to 5 AP, when it should've been 6. After AP Silence expired, it jumped back up to the correct value of 8.

I tested this offline to be sure, and I was right to keep an eye on it. I had a Govulmer inflict AP Silence on a Yasha (2 AP) and played the Grow Guard defense card, which resulted in Yasha dropping to 1 instead of 0; it then returned to 3 after AP Silence expired.

Grow Guard is the only card I've tested this with, and I haven't replicated it several times, but I wanted to submit it before I went to bed. I'll run some further tests if it doesn't get hammered out before I get around to continuing.

**Comment by fuzziqersoftware** [comment]
I tested both of these scenarios online and offline, and it looks to me like newserv's behavior is the same as offline. Govulmer's AP Silence reduces the target's AP by 3 temporarily, so I would expect the Belra Cannon to have 5 AP after the attack.

AP Silence is evaluated before defense effects; in the case of Yasha, the effect can only remove 2 AP instead of 3, so the card is set to 0 AP and Grow Guard then increases that by 1. If the Govulmer attacks the Yasha again later, it ends up with 0 AP (or 1 if Grow Guard is used again).

Let me know I missed something here, or if there are other combinations that don't work properly.

**Comment by SparkeeLecaro** [comment]
Nope, you're good. This was 100% my fault. I wasn't aware that Govulmer's AP Silence was -3 despite the description stating -2. Thanks for investigating this.
