### ISSUE TITLE
PSO BB incorrect username

### ISSUE THREAD

**Issue by mileskanda** [fuzziqersoftware/newserv#138]
Hello fuzziqersoftware.

Username shows as "---" in all locations in game in upper left corner. Maybe I made a mistake in configuration or maybe this is exe client bug? I use Tethealla client.

Thank you very much for such great work.

Best wishes,
Roman

**Comment by mileskanda** [comment]
I have this with 12513 and 12510, on Windows 10 and XP.
As I see, this commit was made six hours ago. How could I update server?

**Comment by mileskanda** [comment]
No, I'm using server on linux VPS.

Recompiled server and created new player with the same name - it is displayed correctly now. But if I copy old player data, it's name is still "---". Perhaps, I should edit .nsc file somehow.

**Comment by mileskanda** [comment]
Hmm, it is so:
![1](https://github.com/fuzziqersoftware/newserv/assets/59159260/34cc4e33-38d7-4918-bc6b-15eb9d0dc8b7)
So maybe I should see in another place.

Anyway, this player doesn't have too much progress in game and I can create new character.

**Comment by mileskanda** [comment]
Made all dots after character name, and it was shown correctly. When I stop game and start again name is "---" again, because of playtime increases and fills bytes in file.
So I set character name in file to "miles" and it is shown any time I start playing. Name of nsc file I shouldn't change because of game won't see it.

@Matt-Swift, thank you for the right direction in this research! We can close this issue.

**Comment by mileskanda** [comment]
Yes, same here.
Maybe we should pay attention to add in readme about name length in 9 characters. Or maybe to discover where correct the code, but why?

**Comment by fuzziqersoftware** [comment]
I think what's happening is that the client is calling wcslen() to check the name length, but since the play_time field comes immediately after the character name, it thinks the play time is part of the character name, so it thinks the character name is too long. I've made a change to work around this client bug by just always sending 0 for the play time, except in the character selection menu. You shouldn't need to re-create any characters; the save data is not affected by this bug.

**Comment by fuzziqersoftware** [comment]
This should be fixed permanently by the rewrite of the text handling abstraction that I did a couple of weeks ago.
