### ISSUE TITLE
[Blue Burst] Loading a quest not included in the server ends up with no EXP from mobs in EP4

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#182]
The server is missing some quests for Episode 4 such as the New Mod Up Operation series and Claire's Deal which is needed to exchange some items for some other items dropped by certain bosses.

I've added both of these quests from the qedit wiki page (.qst extension) and followed the explanation in the README file the quests loaded in game wthout problems, only issue is that any monster they have you attempt to kill it theres an error message saying `Missing BOOTA does not have battle parameter for Episode1` or something like that and you dont earn any EXP

It seems to be the server thinks any other custom quest you add is an Episode 1 quest by default... 

Here's the log of the session
[MissingBOOTADoesNotHaveBattleParamInEp1.txt](https://github.com/fuzziqersoftware/newserv/files/13302453/MissingBOOTADoesNotHaveBattleParamInEp1.txt)

**Comment by Matt-Swift** [comment]
Regarding the other points:

1. The .qst files from qedit.info do not have the episode defined in the header of the .bin file - or rather, it is 00, which flags it up as Episode 1. I believe this may be the case for all of them, but not sure... The client and tools parse the episode from the `set_episode` OPCode when the quest is read, but the server reads the episode from the header, in which the header is wrong in this case (did SEGA define the episode in the header for BB quests? I want to say yes but I can't be 100% sure)
2. There's a lot of missing quests but I'm actually working on dumping them all here somewhat soon, I'm just planning to do it all at once instead of piece by piece.

**Comment by fuzziqersoftware** [comment]
This should be fixed now; see #142 for details.
