### ISSUE TITLE
[Blue Burst] PSOBB Client flags to change Language and Enable/Disable IME

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#196]
PSOBB has a hidden ENG/JPN switch flag to effectively turn the JPBB client into the USBB client and tell the client to properly load all the _e localized files such as unitxt_e , etc. 

Setting this setting back and forth can help debug with ease the new Quest Directory rework by forcing either Japanese or English quests depending on the setting at the client level, it will also change the Prefix of your character and guild card from J to E in the Lobby.

Likewise, for some odd reason the IME in the default TethClient12513 is disabled by default despite it's still the japanese client, I am aware theres also another flag to enable/disable this which probably was enabled by accident when the client was created back in the day. 

PSOBB allows to create characters with English, Japanese and Chinese names, I've been unable to test this functionality because I cannot type in Japanese inside the client at all. 

Sadly my knowledge about how internal flags in the client are read and set is very limited as I absolutely have no idea where to look for to begin with.

By the way, I've been using this [CreateTethEXE_v1.03.zip](https://github.com/fuzziqersoftware/newserv/files/13353978/CreateTethEXE_v1.03.zip) tool to generate the Psobb exe with the adjusted ip/ports it seems to also have a asmpatch tool of sorts that could help modify those flags on the fly, or if you happen to know a more updated tool to adjust the client parameters please let me know over here.

**Comment by Matt-Swift** [comment]
Regarding the IME flag, per the Blue Burst Patch Project patch [here](https://github.com/Solybum/Blue-Burst-Patch-Project/blob/master/Blue%20Burst%20Patch%20Project/ime.h), you would need to change the byte string 9C C3 8E to 86 13 84 - this is at 0x440780 in an unmodified TethVer12513 client. That's if I'm understanding this right anyway - none of the IME patches (including Ephinea's) actually work on my Debian systems so I can't test it out.

Regarding having the client read from _e files instead of _j, I am not too familiar with this and Ephinea does not use this method either - we just serve different localised files (all _j) depending on what people have a registry/account setting set to.

However, newserv forces all clients that begin with TethVer as English per [this part of the code](https://github.com/fuzziqersoftware/newserv/blob/a62b7dad268d426cc60d01cd87e3288b2c94e393/src/ReceiveCommands.cc#L1025) (so, serving English localised files instead of Japanese) even though it's a Japanese client, so you could change the string to something else to make newserv serve Japanese files instead. This string is at 0x56CE20 if you wish to modify it.

**Comment by nolrinale** [comment]
For the client to read the _e files (including fixing the word select) you need to change the internal ENG/JPN flag then the client will just default to load the _e files, schthack achieved this when we were building schtserv last year but I don't have any way to reach him anymore 

Its super convenient because that way you don't need to overwrite any of the _j files in fact not touch them at all, I will see what I can do 

Thank you for finding me the IME one at least for now i can test making character names with japanese see if i break more stuff!!

**Comment by nolrinale** [comment]
@Matt-Swift 
Ok correct me here if I'm wrong, created a new txt file called asmpatch.txt and inside I wrote:
```
SEEK,00440780
WRITE,86 13 84
```
Rebuilt the exe and tried again, IME is detected but wont let me switch to Kana input so i think it's still disabled... 

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/5d48a0a5-0260-4735-a95d-ebfca5b8b4fb)

**Comment by ShiftaDeband** [comment]
Would this language flag also hypothetically change the language/lobby flag to Chinese? I’m wondering if the PSOBB CN client used this flag as well or if it was a heavily modified Japanese client and server. 

If memory serves me, though, it used _c for those language files, but I’m not positive. 

Speaking of, and entirely off topic here, it feels like that client has been lost to time.

**Comment by nolrinale** [comment]
Correct, this flag allows the localization support for J, E and CS I'm currently testing the English flag, I was able to succesfully turn JPBB client into the USBB one but I'm just making sure that there are no weird strings or text issues here and there and/or sudden client crashes. PSOBB likes to crash a lot when it feels a file is off in some way.

However in the case of the Chinese version since it was closed even before the US version the client might be even more outdated so might require some adjustments either way if you have access to the very latest chinese client feel free to make a PR and add a new folder called `cnbb-resources` to the notes folder of the repo and upload there all the _cs files you can find so we have them all centralized in one spot.

**Comment by nolrinale** [comment]
This issue is also related the issue https://github.com/fuzziqersoftware/newserv/issues/180  , which is now fixed, instructions to set all this can be found on `notes/psobb` !
