### ISSUE TITLE
[Blue Burst] EP4 room gets initialized with many UNKNOWN enemies

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#203]
I don't know if this is a bug or not but either loading quests or free exploration Episode 4 room i'm noticing a lot of UNKNOWN enemies entries in the console alongside EP4 monsters and I was wondering if maybe it's referring to the Last Boss's Missiles, Tornadoes, Spinners aren't included here like the Mines from EP2 boss or the Spinners of the EP1 boss or the Bees in the Sub Desert maps?.... 

Here's a snippet 
[EP4InitUnknownEnemies.txt](https://github.com/fuzziqersoftware/newserv/files/13401525/EP4InitUnknownEnemies.txt)

**Comment by Matt-Swift** [comment]
This is just the server loading NPCs. They are not defined by name in the server EnemyType files since they're not really "important", so they are just "unknown" types. There isn't actually any mechanical issue here, as you shouldn't be killing them and rolling any drops from them - at least I hope not.

For example though, 001D is the Guild/Bank Lady.

**Comment by fuzziqersoftware** [comment]
I do intend to fix these at some point, just so the server will know what they are, but it's pretty low on my priority list for the reason Matt described.

**Comment by nolrinale** [comment]
Fair enough closing this one then, wanted to confirm just in case.
