### ISSUE TITLE
[Blue Burst] Blacklisted players chats are still visible by the User

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#232]
If a user blocks a player the chat, symbols and word selects shall be muted, in this case I added by received mail the character RHEA to my blacklist, still after meeting in the lobby I can still see their chat message bubbles.

On top of that the blocked player guild card field turned into a bunch of question marks "?????????????"

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/79af6903-c857-4599-89ee-fe1133e83de6)

**Comment by fuzziqersoftware** [comment]
According to the PSO GC manual at least, Block Sender is only supposed to block Simple Mail and Guild Card search results, not in-lobby chat messages. Some other BB servers may have implemented it such that it blocks chat messages, but that's not vanilla behavior.

I tried blocking a user, and the user's information appeared correctly in the block list (name, class, language, etc.). It still appeared correctly even after I logged off and logged on again. Do you still get "???????" if you try it now?

**Comment by nolrinale** [comment]
No its actually a vanilla behavior , I recall on JPBB ran into an overseas player that was harassing me and the guys taught me how to blacklist, i coulndt see his messages trashtalking me in the lobby (but other people were able to) until sega ultimately banned him entirely for harassment.

**Comment by fuzziqersoftware** [comment]
To summarize an offline discussion from a while ago:
- In-lobby chat wasn't affected by the block list on vanilla
- Simple Mail auto-reply messages now respect the recipient's block list
- The ???? Guild Card info probably happens because the card was blocked from a mail message; if it was added from a Guild Card or an online player, it should have full information and no ????s
