### ISSUE TITLE
[Blue Burst] Gallon's shop is buggy

### ISSUE THREAD

**Issue by toiletman74** [fuzziqersoftware/newserv#248]
The version of gallon's shop that is packed in with the server is buggy. Adding stats to weapons is messed up. It's missing the option to add 1% to an attribute. I used the add 5% button and put in a handgun 0/0/0/0/0 and picked native. Nothing changed though.

**Comment by toiletman74** [comment]
I tried adding native to a weapon in another copy of gallons shop and it also didn't add anything to the weapon. I also noticed that trying to use the $item command in the quest at all makes the client crash on both versions of the quest.

**Comment by fuzziqersoftware** [comment]
The commend is implemented by sending a 6x29 (destroy item) followed by a 6xBE (create inventory item). To my knowledge, it doesn't actually matter what the new item's ID is as long as it isn't in use, which we are sure is true in this case because of the 6x29 command. What potential issue do you foresee here?

**Comment by Matt-Swift** [comment]
This works fine now actually - was able to add attributes to an item in the middle of the inventory, immediately add more right after (with it at the bottom), then I banked the weapon and relogged and everything was as it should be.

Can probably close this ticket.

**Comment by fuzziqersoftware** [comment]
Thanks for testing again.
