### ISSUE TITLE
[Blue Burst] [Feature Request] Disable all $ commands for normal player accounts.

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#258]
For a proper vanilla experience would be a good idea to disable/enable via config.json the usage of all the $ commands for Normal players accounts or at the very least disable the newly added $bank command entirely.

**Comment by fuzziqersoftware** [comment]
It's explicitly not a goal of newserv to replicate the vanilla experience exactly; rather, it's a goal to replicate all of the vanilla functionality. This means that hiding or removing custom functionality solely for the purpose of replicating vanilla behavior is out of scope - it's only within scope if the existence of some custom functionality hides a vanilla behavior, which chat commands do not.

Some commands can already be disabled (e.g. various cheating commands) so the overall experience of the server can be customized. Having the ability to disable chat commands entirely feels unnecessary to me, since it's pretty unlikely an unaware player would stumble across their existence. Is there a specific reason you're concerned about $bank?

**Comment by nolrinale** [comment]
The reason why I dont think the common bank system is a good idea is because I believe storing and shuffling around all those items in the characters save file might end up creating a conflict with other important flags inside the save data blob.

I'm saying this from a position of almost total lack of knowledge about how exactly a charactee save file is structured, but since I've noticed how delicate PSOBB is treating character data and all the bugs we have been discovered and fixed so far thought it would be detrimental for the game stability. 

You are more knowledable than me about the internals, after all, I'm just a player and can only test stuff at a very superficial level. So I would like to know your opinion, is this an unnesessry fear from my side? and theres no way shuffling banks around can mess up with characters data in any way? what about messing around with $bank during a battle or cmode?

**Comment by fuzziqersoftware** [comment]
It's easy to mess things up if we treat save data as a mostly-opaque blob, but we don't do this; newserv has the structure fully defined. Because of this, we don't need to copy any data when switching banks - when you switch to another character's bank, the other character is actually loaded as if it were in play, and you access that character's bank instead of your own. The shared bank is implemented in a similar way; it's essentially an overlay on top of your character's data. I don't think anything could break in normal play as a result of using shared banks; quest flags and such are entirely unaffected.

I've disabled $bank when a character overlay is present (that is, when a battle or challenge quest is in progress), even though players shouldn't be able to access the bank at all during those times. Using $bank in a battle or challenge mode game before loading the battle or challenge quest still works normally.

**Comment by nolrinale** [comment]
Perfect thank you so much for the explanation its all clear now that is totally safe so i'm closing this issue
