### ISSUE TITLE
[Feature request] Individual drops

### ISSUE THREAD

**Issue by toiletman74** [fuzziqersoftware/newserv#270]
The option to turn on individual drops in bb would be a really nice addition. Most servers have that option so going back to shared drops feels weird.

**Comment by fuzziqersoftware** [comment]
This has been on my to-do list for a while, but it's a fair amount of work, so it will likely take a while to implement.

**Comment by nolrinale** [comment]
As long it can be disabled via config.json im fine with it, but is not a vanilla behavior.

**Comment by fuzziqersoftware** [comment]
This is my project, so it's up to me to decide what should and should not be included. That said, I agree that preserving the original behavior is important; when individual drops are added, they will be gated behind a config option and/or chat command.

**Comment by fuzziqersoftware** [comment]
There are now five drop modes implemented - see the "Item tables and drop modes" section of the readme for details. The default behavior is to use vanilla shared drops, but players are allowed to switch to individual (private) drops or duplicate drops as well. The default and allowed modes can be changed in config.json.

One other change that comes along with this is that the server now handles pick up item requests instead of the leader on all versions, not just BB. This means that if the leader's connection is slow, other players will no longer see delays in picking up items.

I did some basic testing on DC/PC, GC, and BB in private and duplicate modes, and everything seems to work, but the code is fairly complex and there could still be bugs. Please report any issues you see when using these modes.
