### ISSUE TITLE
[PSOPC] Rare monster rates in config.json don't seem to work

### ISSUE THREAD

**Issue by toiletman74** [fuzziqersoftware/newserv#281]
I tried setting lilies on hard to always be rare but on psopc they weren't. I tested it on blue burst and it did work correctly there. I didn't test it out on any other versions.

**Comment by Matt-Swift** [comment]
They can't - the client is what determines rare enemies in non-BB versions, as such newserv cannot do this for you, you would have to modify the game itself in some way.

**Comment by fuzziqersoftware** [comment]
The comment in config.json specifies that that field applies only to BB games, since (as Matt said) this is controlled by the client on all other versions. The only way to force rare enemies to appear on non-BB versions would be to find a seed value that causes a specific enemy to be rare, then use that value with $rand before creating a game.

**Comment by toiletman74** [comment]
ah I see
