### ISSUE TITLE
[Episode 3] 00A1 "Concentration" does not work properly

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#285]
00A1 "Concentration" is a connect card that links with a technique to double the TP of the technique card with the ability "Tech x2". This doesn't seem to be working, as the damage dealt as if it concentration was never played.

Tested offline and it works as intended. Also tested online with Nei's Claw which has the same ability, although the parameters are slightly different.

Log below of using the card with Foie, the log should start slightly before and end slightly afterwards.

[Concentration.txt](https://github.com/fuzziqersoftware/newserv/files/13757321/Concentration.txt)

**Comment by fuzziqersoftware** [comment]
This is fixed by 2ee6119c. The ktp and kap tokens in special effect expressions were computed incorrectly - we would ignore all action cards, instead of only action cards before the relevant card. This bug probably also affected Rika's Claw +, Charge, Rufina, and Sinow Zele (though Rufina and SZ may have worked properly because the effect was on the attacker card instead of an item or action card - I didn't check this).
