### ISSUE TITLE
Is is possible to run multiple instances of newserv on one server? (Linux)

### ISSUE THREAD

**Issue by MADrewry** [fuzziqersoftware/newserv#308]
I was attempting to run two instances of newserv on my linux box using tmux. Each server is in its own directory and I set the config.json of each server to separate network interfaces (eth0 and wlan0 respectively) One instance will run fine but when I start the second instance I receive the error below:

I 775 2023-12-31 21:16:57 - [Config] Starting DNS server on port 53
I 775 2023-12-31 21:16:57 - [Config] Opening sockets
I 775 2023-12-31 21:16:57 - [Config] Starting proxy server
terminate called after throwing an instance of 'std::runtime_error'
  what():  can't bind socket to 0.0.0.0:5123: 98 (Unknown error)
Aborted

Other than the "LocalAddress" line in config.json I don't see any other place to bind interfaces. It is possible to configure newserv to run multiple instances on the same device?

**Comment by fuzziqersoftware** [comment]
This is likely because the server always listens on all interfaces - LocalAddress and ExternalAddress just tell the server where to tell PSO clients to reconnect to when they change servers. I haven't considered the multiple-instances use case before, but I've pushed 4ff4c86 which allows you to specify interfaces for each listener and the DNS server. You'll probably want to specify the same interface for each listening port. I haven't tested this very much, so please try it out and let me know if you run into any issues.

**Comment by MADrewry** [comment]
Wow! wasn't expecting such a quick response on this, Built the latest commit and updated my config.json, but server will not start, errors out with the following:

terminate called after throwing an instance of 'std::runtime_error'
  what():  cannot parse item description "Tablet" (as text: item not found: tablet) (as data: data is too short)
Aborted

Reverted to my original config.json with the same error. Did I miss something else?

**Comment by fuzziqersoftware** [comment]
The way item names are resolved was changed in a recent commit, and it's likely that your configuration refers to an item that the server can no longer resolve. Specifically, if you have a BB patch tree set up in system/patch-bb, the server will look in its unitxt files for item names and match them up with the entries in its ItemPMT file to generate an index. In your case, presumably "Tablet" isn't defined in the files in your BB patch tree... try pulling master again, then build and run `./newserv name-all-items` to see the contents of the server's item name index. In my instance, Tablet is defined on line 031800; if you have something else defined on that line, you can change your config.json entry to match your index.

**Comment by nolrinale** [comment]
For this issue, what about implementing the functionality of having ships with blocks?

**Comment by fuzziqersoftware** [comment]
I would guess the use case here is to run different configurations on each - maybe one is a public-facing server and the other is used for testing things, so it would have e.g. cheat mode enabled and would have licenses with more permission flags set.

Re: multi-block ships; newserv's design philosophy doesn't really align well here. The general principle behind its design is that the PSO community is small enough these days that a single server can handle any situation that would reasonably arise, and newserv can already deal with all lobbies being full by creating private overflow lobbies on demand (though I can't imagine this would ever actually happen). It seems most other servers use a login server + lobby server split design, but this level of complexity seemed unnecessary to me even in 2010.

**Comment by nolrinale** [comment]
I honestly prefer the current way too, but I thought it would be a solution to aggregate servers in a single ship list in case anyone wants to host more than 1 newserv instance.

But also running more than 1 newserv instance in a box seems a little overkill to me anyways, the player count isn't just there anyways.

**Comment by ShiftaDeband** [comment]
My two cents: I really enjoy the idea of seeing the old ship and block select screens. That's probably the only thing I miss when logging in. I know it's silly, and I agree with your design philosophy. But if it were to ever show back up one day, I wouldn't mind. 😄 

However, in my mind and current use case, I can't think of a reason why I would have a separate ship for anything, since so much happens before this. And even then, wouldn't the Ship and Blocks be tied to the instance as a whole? Especially with Blue Burst. (I guess you could see a config setting to enable more ships/blocks if you have the specs, but -- for what?)

One neat idea that's already implemented, and if you haven't already: connect to one of your instances, call that one your default/main instance, then add the other ship as a proxy destination. (and vice versa so you can go back and forth if you ever need).

**Comment by MADrewry** [comment]
Apologize for the delayed response, it's been a busy day. I haven't been able to test multiple instances yet; I pulled master and ran ./newserv name-all-items as requested. I noticed that there appears to a lot of missing data in my patch files, which may be the cause of my original issue. Not sure what I have done as I haven't changed the patch files at all recently. This happens on both of my instances, one with @nolrinale's Teth client files and one with the 1.24.3 client files. I have been scratching my head but haven't been able to figure out how to resolve it. I have included the log file, maybe you can see what I cannot.

To add my bit to the interesting conversation, @fuzziqersoftware is correct that in my case multiple instancing is for testing purposes only. Yes for nostalgia's sake seeing ship and block screens would be fun, but I agree it is totally unnecessary with today's PSO population. I like the simplicity of newserv which is why I was drawn to it.

[log.zip](https://github.com/fuzziqersoftware/newserv/files/13806907/log.zip)

**Comment by MADrewry** [comment]
Ok, just so I could test the multiple instances I removed all of my BB patch data to get the servers to run. I was able to start one instance, when starting the second instance all of the ports bound to the second interface except for the Xbox login server, I got the following error:

terminate called after throwing an instance of 'std::runtime_error'
  what():  can't bind socket to 192.168.86.110:9500: 98 (Unknown error)
Aborted

I verified the syntax was correct in config.json so that wasn't an issue. However I did find that commenting out that line allowed the server to start.
I did a quick test and I was able to successfully connect to both instances of the server from different BB clients. So Yay that works!
