### ISSUE TITLE
[DCNTE] Cannot register SN/AK

### ISSUE THREAD

**Issue by ShiftaDeband** [fuzziqersoftware/newserv#313]
Good afternoon,

It appears that serial number validation is not working for Dreamcast NTE clients. My instance is [throwing an error on this line](https://github.com/fuzziqersoftware/newserv/blob/4f650bebf0db7e78b177d4258f80ed58251122bd/src/ReceiveCommands.cc#L470) when using a legitimate SN/AK for the NTE. The NTE SN/AKs are [ridiculously long](https://www.ebay.com/itm/256215164694?hash=item3ba79d2716:g:hWcAAOSwhD5k~17G&amdata=enc%3AAQAIAAAA8AJAQlMRI8x4crW%2FexXvLXWIAkihdE6kKb%2FDfH0os61WqqXfluA8ZFLMZosYtoKWWINhIQAMUI17kF53woLHDAr7UmD93pqlFJqwrXD9rpcRY%2FIJFvpsz57R2eqpe5v8UAufUprxaGVBzL%2BRPlzXyab2YMOWsJkfvRDlbdyt9%2BvMi%2FrPC51xCQugny4r21cZHUzkarhp81hHPfw6xQxhqIvfUKLrbXGjJIG9Yo8FvdVY4%2FG0ddX0rzknNXRGeiD0pQH07fHXr0gGU81PSsk3%2F4cm8XiKNyrbGs8fYe9WQ5pQ4zgwaL1dk2Dug22%2FMCZPxQ%3D%3D%7Ctkp%3ABFBMxPSTyplj) and do not seem to pass newserv's check, including in the command line.

I was able to (temporially) bypass by using the same logic as the line below it.

Happy to provide a log if needed. Thank you as always for everything you do.

**Comment by fuzziqersoftware** [comment]
NTE SN/AK pairs are indeed too long because the server expects exactly 8 characters for both (but if you enter only 8 characters on the NTE client's SN/AK screens, the client does accept the shorter strings and it works on the server side too). It's a known issue that the server rejects longer credentials; I'll leave this open to track the fix.

**Comment by nolrinale** [comment]
It seems its related also to the original PSOBB client limit of 8 chars for pass and username, what will happen with this issue?

**Comment by fuzziqersoftware** [comment]
This is not related to the PSOBB credential length limit; BB uses different fields in the License object. The main issue here is what should happen for NTE users if they want to share a SN/AK with another version. Currently you can use the same SN/AK on all versions except Xbox and BB if you want to, and you can do this on DC NTE as well if you enter only 8 characters. So should we only check the first 8 characters, but allow longer credentials, or should we require 16-character credentials and essentially separate the credential space from the other versions? I think what I'll end up doing here is allowing credential sharing if you enter 8 characters, and if you enter more, then you get a temporary license instead.

This has been a fairly low priority since NTE users can still play without this being fixed, but I intend to get to it eventually.

**Comment by ShiftaDeband** [comment]
The only issue with that is that then those saves become incompatible with other servers (Sylverant) which requires a registered SN/AK. 

I can't recall if this version saves the SN/AK to the system, though. It could be solved with multiple memory cards, but even then, longer term, this would help keep consistent across the different environments. 

My two cents.

**Comment by nolrinale** [comment]
Ah I totally forgot about that, then you will have to allow 16 and create a temporary license on the fly on newserv so people can quickly transfer between their newserv instances and the public server like sylverant or scht

Totally forgot you could use the same memory card for various servers at the same time

**Comment by fuzziqersoftware** [comment]
This has been implemented. DC NTE licenses don't share their SN/AK space with any other version; if you want to share a license across versions, you'll have to add the `dc-nte-serial-number` and `dc-nte-access-key` fields using `add-license` or `update-license`.
