### ISSUE TITLE
[Blue Burst] Characters which haven't completed any Gov quest can join other Gov Quests regardless of progress

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#319]
Player 1 creates an episode 2 normal room and load quest 7-4 normal difficulty
![Screenshot from 2024-01-04 16-18-21](https://github.com/fuzziqersoftware/newserv/assets/5244595/47efb9f9-b971-4973-ac57-75a5ccd10264)

Player 2 haven't completed any EP2 quests yet (so only has 5-1 available)
Player 2 attempts to join Player 1 room which si running 7-4

![Screenshot from 2024-01-04 16-18-29](https://github.com/fuzziqersoftware/newserv/assets/5244595/57cb37cf-01ff-4027-8ca6-9e0026aaae00)

Player 2 is able to join skipping all the gov questline altogether
![Screenshot from 2024-01-04 16-18-46](https://github.com/fuzziqersoftware/newserv/assets/5244595/20de3da7-28de-4bfe-9a52-0a72e96ed3d9)

The correct behavior is, in the lobby if Player 2 havent completed the quest the room should appear greyed out in the Information Counter list, and upon trying to access a error message stating the quests up to host players point havent be completed yet should appear.

**Comment by fuzziqersoftware** [comment]
This has been fixed by 4be43147. All games that cannot be joined for any reason (full, level too low, no access to quest, etc.) will be grayed out in the game menu, except for games in which a player is currently loading and will be joinable soon. This behavior may technically differ from vanilla behavior, but I believe this behavior will be more aligned with players' expectations.
