### ISSUE TITLE
[General] Running any reload command appears to reload a lot of other things

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#329]
**Describe the bug**
After running a command such as `reload patch-indexes`, the server will also reload things like the config file and quest data.

**To reproduce**
Type `reload` anything!

**Server log output**
[example.txt](https://github.com/fuzziqersoftware/newserv/files/13851960/example.txt)

**Comment by fuzziqersoftware** [comment]
This is actually intentional. There's a dependency graph defined in the ServerState object, so that reloading any dataset will also reload anything that depends on that dataset. For example, parsing the config file depends on the ability to resolve item names to IDs, which depends on the item parameter tables. So `reload item-parameter-table` will cause the item name indexes and config file to be reloaded as well, to ensure that the items defined in it still make sense with the new ItemPMT tables. Unfortunately, the config node depends on a lot of other nodes, so many actions will cause the config node to reload as well. And the quests node depends on the config node, since the quest categories are defined in config.json.

To resolve this, probably I'll split the config node into many subnodes representing different parts of the configuration, so the dependencies can be less entangled.

**Comment by Matt-Swift** [comment]
After the most recent commit, I'm assuming this one can be closed? I did a few reloads recently and this doesn't seem to occur at all anymore - although with the split threads it's not like it matters

**Comment by fuzziqersoftware** [comment]
Yes, load step dependencies have been removed, so the reload command once again only reloads the thing(s) you specified.
