### ISSUE TITLE
Where to get the Item names and hex list for V3 ? (names-v3.json was deleted recently)

### ISSUE THREAD

**Issue by Keklul404** [fuzziqersoftware/newserv#331]
Hi,

https://github.com/fuzziqersoftware/newserv/blob/master/system/item-tables/names-v3.json

I was using that file to get the list of names and hex from V3 for a tool I was writing, but I saw that it got deleted.

So I was wondering, which files on GC and Xbox store that list ? (item names and hex)

**Comment by Matt-Swift** [comment]
https://github.com/fuzziqersoftware/newserv/blob/5ba652aa381d431fb046f400eb1d431f5ff64af5/system/item-tables/names-v3.json

**Comment by Matt-Swift** [comment]
It's a list of the items from itempmt.PRS, yes, with the text strings from unitxt_e.prs

**Comment by fuzziqersoftware** [comment]
You can still use names-v3.json if you get it from the git history - the file is accurate and always will be, since it reflects the canonical list of items on the v3 client. It was deleted from newserv only because the server doesn't use it anymore.

To build the names-v3 list yourself, you'd need TextEnglish.prs and ItemPMT.prs; the formats of those files are documented in TextIndex.hh and ItemParameterTable.hh. It would be tedious to rewrite parsers for both if all you need are the item names, so I'd recommend using names-v3.json anyway.

**Comment by fuzziqersoftware** [comment]
I've reverted the deletion (so names-v3.json is now present on master again), since I feel like these files will be useful for development and debugging even though the server doesn't use them.
