### ISSUE TITLE
[EpIII NTE] Cannot go back to lobby when leaving a game

### ISSUE THREAD

**Issue by ShiftaDeband** [fuzziqersoftware/newserv#335]
**Describe the bug**
Understanding that the Episode III NTE is mostly unsupported, I was reluctant to note this issue. However, for the sake of completeness, I wanted to at least log it.

When an Episode III client creates or joins a game and eventually leaves from the 'Lobby' teleporter, the game will disconnect at the lobby overview screen when being teleported between the Lobby Teleporter -> Lobby Overhead View -> Actual Lobby.

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Connect to server
2. Create a game
3. Leave game lobby via the teleporter
4. Game will disconnect with an error `[Server] Error processing client command: unordered_map::at`

**Game version(s) (choose one or more of the following):**
GC Ep. III NTE

**Server log output**
[EpIIINTE_Lobby.txt](https://github.com/fuzziqersoftware/newserv/files/13914696/EpIIINTE_Lobby.txt)

**Additional context**
I understand that the Episode III NTE is likely extremely low priority. I hope that one day we could see battles make an appearance? Although with all the server-side craziness that Episode III is known for (and the absolute banger amount of bugs that were logged even when it was live!) I assume it's likely a 'maybe one day' type of thing, or even less. Would love to help however I can if possible.

**Comment by fuzziqersoftware** [comment]
Also re: Trial Edition battle support - this is unfortunately pretty low on the priority list due to how large of an undertaking it is. Supporting card battles for the main game was a fairly intensive reverse-engineering project, followed by quite a bit more testing and fixes. I would like to support Trial Edition battles eventually, but if it ever happens, it probably won't be soon.
