### ISSUE TITLE
[GC NTE] Frequent disconnects when not actively moving, regardless of client timeout setting

### ISSUE THREAD

**Issue by ShiftaDeband** [fuzziqersoftware/newserv#345]
**Describe the bug**
While in the GC NTE and loaded into any game, lobby, map, or even the ship select screen, the game will often prompt the user that they are about to be disconnected. Even with moving the player to send a command to the server, it may disconnect the user randomly. 

Notable is that even with the timeout in the client set to 60 minutes, the prompt will appear with a countdown - e.g. 3547 seconds until disconnect. 

The client will send a disconnect command, and the server will remove the client.

This will sound strange, but it's possibly related to the following commands that the client requests, and the server response. When I call this command, it reliably seems to prompt shortly afterward, probably ~10 seconds or so.

In Lobby: `B1 00 04 00`
```
I 22266 2024-01-17 19:59:44 - [Commands] Received from C-7 (version=GC_NTE command=96 flag=00)
0000 | 96 00 0C 00 96 B2 57 C6 37 00 00 00             |       W 7       
I 22266 2024-01-17 19:59:44 - [Commands] Sending to C-7 (version=GC_NTE command=B1 flag=00)
0000 | B1 00 1C 00 32 30 32 34 3A 30 31 3A 31 38 3A 20 |     2024:01:18: 
0010 | 30 32 3A 35 39 3A 34 34 2E 30 30 30             | 02:59:44.000    
I 22266 2024-01-17 19:59:44 - [Commands] Received from C-7 (version=GC_NTE command=99 flag=00)
0000 | 99 00 04 00                                     |                 
```

In Game: `6F 00 04 00`, seems to be requested at least when joining a game and maybe occasionally during the game?
```
I 22266 2024-01-17 19:57:00 - [Commands] Received from C-6 (Test) (version=GC_NTE command=6F flag=00)
0000 | 6F 00 04 00                                     | o               
I 22266 2024-01-17 19:57:00 - [Commands] Sending to C-6 (Test) (version=GC_NTE command=B1 flag=00)
0000 | B1 00 1C 00 32 30 32 34 3A 30 31 3A 31 38 3A 20 |     2024:01:18: 
0010 | 30 32 3A 35 37 3A 30 30 2E 30 30 30             | 02:57:00.000    
I 22266 2024-01-17 19:57:02 - [Commands] Received from C-6 (Test) (version=GC_NTE command=99 flag=00)
0000 | 99 00 04 00                                     |                 
```

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Connect to server with a GC NTE client, which is difficult as it requires the modem or Wii with Devolution.
2. You can see this bug as early as the 'ship select' screen.
3. The commands above, depending on context, can also reproduce the behavior.

**Game version(s) (choose one or more of the following):**
GC NTE

**Server log output**
Here's the log: [ntedisconnect.txt](https://github.com/fuzziqersoftware/newserv/files/13971644/ntedisconnect.txt)

**Additional context**
I'm in the process of trying to determine if this is a client bug or if there's a command that the GCNTE expects, but I wanted to log this in case you have any ideas. (I'm leaning toward this being a client bug, but haven't done much investigation if I can find any complaints about this either on old social media, the PSO minhiro BBS from the trial, etc.)

**Addendum**
I'm going to take this time to make a plug for those who would like to test the GC NTE, since it isn't super accessible.

There are currently two options: Wii, using Devolution with a custom slirp server set up with slirp and socat, and [dreampi](https://dreamcastlive.net/downloads/) with the [cubepi addon](https://github.com/ShiftaDeband/cubepi) -- at least in the very near future.

Devolution is absolutely the 'easiest' since all you need is a Wii and something like a Raspberry Pi or some kind of server Linux distro (Ubuntu server comes to mind) and [following the instructions that I wrote up](https://github.com/ShiftaDeband/Devolution-slirp-Modem-Emulation-Guide). 

Since Devolution typically requires a physical disc to validate the ISO file you're using, I'd suggest taking a peek at [alternative sources](https://gbatemp.net/threads/defeating-devolution.615252/post-10105355) and use that version, and finding the ISO for the GameCube Trial Edition at another alternative source.

However, if you have a GameCube and:
- a modem adapter
- a dreampi set up
- and either:
    - a way to load homebrew/backups
    - the physical game with either a Japanese GameCube, region switch mod, or Action Replay/Freeloader

... you may be interested using DreamPi with the CubePi added on. 

As of last night, I finally figured out why the Trial Edition and JP v1.0 wouldn't work. In the end, it looks like these versions require some kind of authentication (either PAP or CHAP) before they'll accept the PPP link. That part is coming soon to my [CubePi fork and utility](https://github.com/ShiftaDeband/cubepi) (and hopefully someday incorporated into the DreamPi DLE release itself), but will take a few days. Please check that project if you're interested.

I don't believe you can use Dolphin and Devolution to do this on a PC. Last time I tried that, it hung, which isn't too surprising, but I didn't dig into that too much. 

**Photos**
![IMG_0410](https://github.com/fuzziqersoftware/newserv/assets/40249870/3235f2c6-e3a4-4295-ae4b-3235f6986872)
![img2](https://github.com/fuzziqersoftware/newserv/assets/40249870/407fa6bb-d086-4edf-80e5-f818c659dab0)

**Comment by ShiftaDeband** [comment]
I should also note that this version also has an option for UDP. You can set it to auto, on, or off. I have set mine to off. I don't expect this to have much impact, but I'm throwing this in here just in case it matters.

Testing with this setting in different configurations does not seem to make much of a difference at least with this bug specifically. I'm not sure what this setting is set to on the retail versions.

**Comment by fuzziqersoftware** [comment]
I suspect this is a client bug, but it's possible something the server sends is triggering it. The B1 command is used to synchronize the client's timestamp with the server; do your GameCube and server have significantly different system times? newserv sends the B1 command much more often than strictly necessary, so this could be triggering the issue on the client. I'll play around with some of the client settings to see if I can make this happen myself.

For those willing to build Dolphin themselves (not for the faint of heart) you can use [this unmerged PR](https://github.com/dolphin-emu/dolphin/pull/12355) that adds modem support. This is how I've been testing GC NTE myself.

**Comment by fuzziqersoftware** [comment]
Also, can you show what all the settings in your character's options menu are? Specifically the line timeout option - there are normally 4 line timeout options (15, 30, 45, and 60 minutes), but in the final game, there are 4 more unused options, which are 0, 0, 16, and 32 seconds, respectively. I wonder if the game somehow messed up your option flags and is using one of the extra-short line timeouts?

**Comment by ShiftaDeband** [comment]
What a weird thing. 

Thank you for the callout on the GameCube's system time/RTC. It looks like this GameCube's CMOS battery is toast as the date and time keep getting scrambled. I swapped over to using one that has a working battery and ordered replacements for all of them, since I doubt this one has much time left as well.

So far, I've tried:
- Setting GameCube date/time to local, UTC, JST
- Making sure the 'line timeout' is set to 99
- Setting the game's disconnect setting to different options (15/30/45/60)
- Setting UDP between Auto, On, and Off

What I haven't tried:
- Checking behavior beyond ship select on Wii/Devolution
- Behavior on that branch of Dolphin

It's looking very likely that this is something on my end, possibly with the modem setup, GameCube CMOS, or even something else in network, if you're unable to replicate this.

As for timeouts, they are the same as final. We're going back to the early 2000s sharing these images since I still haven't set up my capture card:
![IMG_0415](https://github.com/fuzziqersoftware/newserv/assets/40249870/d73de6c4-bce1-4e75-81f3-2c518504e28c)

**Comment by fuzziqersoftware** [comment]
I've observed this behavior on Dolphin now, but it's very unreliable: sometimes it will occur within 30 seconds of joining a new game, and sometimes it won't occur at all. I still suspect a client bug since the server has little to do with how the client handles timing, but I've looked through the logic for the TDialCut object (which is responsible for idle disconnects) in Ghidra and haven't found any obvious bugs yet. I did catch the client once with a value for last_update_time that was about 2 years in the future, which triggered the bug, but I don't yet know where that incorrect value came from.

Tangentially, I did discover one weird thing though as a result of this: there is a 24-bit flags field in the B1 command in V3 and later, which controls a couple of client behaviors that I previously thought were just automatic.

**Comment by fuzziqersoftware** [comment]
This is an amusing bug. It turns out it only occurs during the month of January.

There is a structure `LocalTime` representing the current time, similar to the standard `struct tm` but with less precision: it stores only year, month, day of month, hour, minute, and second. There is an accompanying function, which we call `compute_psogc_timestamp`, that converts this time into a Unix-like timestamp (its zero point is January 1, 2000 instead of January 1, 1970). The TDialCut object uses this structure and function to determine the current time, then subtracts the time of the last controller input to find out how many seconds the controller has been idle. (Side note: it appears only buttons and the left stick are counted here; moving the C stick doesn't count as not being idle.) If the idle time is within 30 seconds of the limit, it shows the warning window; if the warning window is already visible and the idle time is past the limit, it disconnects. These two cannot happen on the same frame, so if the idle time suddenly jumps to a very high value, it actually takes two frames to disconnect.

`compute_psogc_timestamp` needs to know the start date of each month, since `LocalTime` doesn't have a day-of-year field. There is a static 12-entry lookup table that the function uses, and it manually adjusts for leap years before using this table.

It appears there are two bugs which combine to produce the broken behavior. The first is that the month field in `LocalTime` is zero-based (that is, January is 0, not 1), which is not the case in the final version of PSO GC. `compute_psogc_timestamp` assumes January is 1, so it indexes into the lookup table at `[month - 1]`, which reads an entry out of bounds. However, since the lookup table is in the static read-only memory region, this should be OK - the value will be wrong, but it will always be wrong by the same amount, and since only the difference between two timestamps matters, the idle disconnect behavior should still work properly.

This is where the second bug comes into play. `compute_psogc_timestamp` doesn't actually use the static lookup table - it copies the entire table into its stack frame, then reads one value from it there. (This is likely the result of the programmer doing something like `int month_start_day[12] = {0, 31, ...}` without declaring it as `static`.) This means that in January, the function will read an uninitialized value from the stack, which is much more volatile. The value that ends up being read is in the space reserved for the frame pointer for any functions called by `compute_psogc_timestamp`, but `compute_psogc_timestamp` doesn't call any other functions, so it remains uninitialized. This all happens during a sweep of calling `update` on all objects, but it turns out that most of the time, the value is consistent because objects aren't created or destroyed in places that would affect the result. But sometimes, usually shortly after joining a lobby or game, objects are updated in a different order, and a different value ends up in this uninitialized space on the stack, so TDialCut thinks 2.5 years have passed in a single frame and shows the disconnect warning or disconnects the player.

I believe the Action Replay code 801E2AC8 38C10008 will fix this bug.

**Comment by ShiftaDeband** [comment]
That's absolutely crazy. Huge props for figuring that out. Would something like faking the month only for the NTE also resolve the behavior at all? (aka. does it assume December is really November?) Along those lines, does the set date/time even matter to the game?

Side note, thank you for contributing to Dolphin. Got the build working and really appreciate being able to test all this easier. Genuinely -- thank you for everything you do.

I believe your initial mission was something along unlocking the oddities and secrets of the series, and this is an incredibly interesting one, and very well explained. (grateful this one never happened to be an issue in retail releases!)

**Comment by fuzziqersoftware** [comment]
Changing the month would work around this bug, but yes, the game would think February was January, March was February, etc. The game uses these timestamps for a few things, probably the most noticeable of which is the Internet Time indicator. So I doubt anyone would notice if it weren't for this bug.

Re: the Dolphin PR, I expected a lot more pushback than I got, which was nice. I need to become less lazy and rewrite it according to their review comments so I can finally merge. Hopefully I'll find the time soon...
