### ISSUE TITLE
[Blue Burst] Enforce Limit of 8 characters max for Usernames/Passwords for BB

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#355]
**Describe the bug**
The Tethealla client is modified to accept 16 characters in the login screen username and password fields, however in the original client this limit is up to 8 characters only, for both Username and Password

Accounts created with the Tethealla client exceeding more than 8 characters cannot login with the official client due to this issue.

**Comment by Elixir70** [comment]
How do you know the limit was 8 characters? Correct me if I'm wrong, but I thought the other client still has the game guard issue so it can't be run at the moment.

I doubt Teth patched this because PSOBB patching back then was primitive and this would be a really tedious patch to implement properly. Or maybe the UI had a limit of 8 but the rest of the client supports more?

Even if this was a Teth patch, is there any harm in it? All players on a server should be using the same client anyway. And even though it's only a private server for a video game, a max of 8 characters for a password is not secure at all.

**Comment by fuzziqersoftware** [comment]
I agree; I doubt this will be a problem for anyone except those of us who are changing clients and testing things frequently; the average player won't run into this in any reasonable circumstance. In the similar case of the DC NTE credentials (#313), the server does need to handle longer credentials because legitimate credentials for that version are actually 16 characters, but in this case, a shorter limit on the client side doesn't affect correctness on the server side.
