### ISSUE TITLE
[newserv] [Feature Request] Implement SHIP/BLOCK system

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#363]
In the previous https://github.com/fuzziqersoftware/newserv/issues/362 ticket we talked about custom lobbies but I think a more sensible approach to this would be to enable/disable events on a per SHIP basis, that means creating different ships with different events rather than splitting them across lobbies.

Effectively restoring the original game SHIP/BLOCK behavior to tackle this challenge

**Comment by fuzziqersoftware** [comment]
There are a few reasons why federated architecture is low on the priority list, but I've never enumerated them publicly, so I'll do so here.

Federated servers would be pretty difficult to implement correctly, since there's a lot of data that would need to be synced from the ship servers to the login server (which would manage the players and PSOBB data server). Parts of the codebase that currently use files on disk would have to be rearchitected to fetch data from a remote server instead, which requires blocking the client in places where we currently don't do so. Dynamic reloading presents another challenge here which is harder in a distributed environment.

I can think of three main motivations for federation:
* Handling large player counts. I suspect the PSO community isn't large enough to warrant multiple ships or blocks in a single server anymore (except perhaps in Ephinea), so this will likely never be an issue for newserv. The server already supports private lobbies and sorts the game list, so it should be able to gracefully handle cases where a large number of players (hundreds) are online.
* Region colocation. It's better to play with a server physically near than one on a different continent, for lower ping times. Ping times are noticeable in PSO but affect the game less than some other, more modern games, so in my mind this is also not a pressing reason to implement federation.
* Content or configuration differences. This is the reason you mentioned, which seems like the most relevant reason to implement this, but given the above, I can't guarantee it will happen anytime soon.

I'll leave this open to track the request, with the understanding that it will not be done in the near future.

**Comment by nolrinale** [comment]
Always theres a chance one of the main servers fail or suddenly close can be Ephinea, Schtserv, Ultima, etc. Remember these servers are all closed source as well. 

Thats why its important to implement this system regardless, even if right now theres no real necessity for it is yet another core game system that is no different than creating a room, handling a drop, creating a team, etc.

**Comment by fuzziqersoftware** [comment]
After thinking about it more, I've decided that separating ships and blocks would contradict one of the fundamental design goals of the project. newserv is designed to be as easy to administer as possible, which makes it a good tool for testing and hosting small servers. As I said above, newserv is not designed for large scale because I doubt such design will ever be necessary given the size of the community, but even if all v1/v2/v3 players today were to play on a single instance, it should be able to handle the computational load with some simple configuration changes (e.g. disabling command logging).

To summarize my thoughts on the question overall, the benefits of federated design would be:
* Ability to span across regions for player colocation and better ping times
* Ability to split load across multiple instances (though I suspect this would never be an issue even in the current design)
* Ability to host different collections of content within the same logical "server" (this can already be done with the proxy server, though that increases ping times)
* Resembling the original Sega servers more closely

The drawbacks would be:
* Time required to implement and debug the federated logic itself
* Permanent slowdown in other areas of development (all data file accesses would then have to consider the federated case as well as the local case)
* Increased difficulty for the average user to set up a new instance

The drawbacks far outweigh the benefits, so we will not implement a federated architecture in this project.

**Comment by nolrinale** [comment]
So that means newserv will be forever capped at 195 players max? 

1 lobby can accept up to 13 players in it
