### ISSUE TITLE
[newserv] [Feature Request] Command to display earned extra currencies

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#365]
I would like to have a small command to quickly display in-game other currencies I have earned from various quests, such as Lucky Coins from doing Phantasmal World or the amount of Tickets earned from the Maximum Attack quests

**Comment by fuzziqersoftware** [comment]
Is there a list of the quest-related currencies anywhere? Most of these are stored in quest counters; I recall seeing a list of all the used quest counters somewhere (maybe called "global flags"), but I can't find it now.

**Comment by nolrinale** [comment]
May need more information for this one as I have no clue besides the currencies used in Phantasmal World and Maximum Attack

**Comment by Elixir70** [comment]
I made an addon for this for BB years ago with a fair number of default flags and masks: https://github.com/Elixir70/psobbglobalflagsreaderaddon/blob/39feaa87efcb34be589810961b62e1ac19e697ac/Global%20Flags%20Reader/init.lua#L23

And Ives posted a list here: https://www.pioneer2.net/community/threads/universal-flags-resource-ufr-chuzzle-threak.14383/post-125147

There are probably some issues between versions for questions that didn't officially exist like MA4 on V2/V3. On BB, there's some overlap between event quests MA1/MA2 hearts and AOL Cup -Sunset Base- which can cause interesting interactions between the quests--no idea if this problem is in other versions.

I recall hearing about some other differences but can't find anything that stands out.

**Comment by nolrinale** [comment]
I checked the list Aleron posted in that thread, and also checked yours and it seems to be is missing the Weapon Shield series that are given in the Sunset Base quest at least in the JPBB one not sure about the AOL one but should be the same in English.

You are supposed to get the shields by throwing the golden badges to the ruins waterfall in the quest, you earn the badges by breaking the final boxes during the Maximum Attack quest (EDY or AOL versions) killing 500 monsters or more in Hard mode or above.

You can get either the Weapon Shield Bronze, Silver and Gold if you keep throwing gold badges to the waterfall, but you can get only 1 of each per character so probably these are the flags are having a conflict from what you just mentioned. 

Weapon Shield Gold
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/fb3be7b8-3b34-429c-9eee-8c85aec621d3)
http://psobb.xrea.tk/droplist/itemdata/item31012613.html

Weapon Shield Silver
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/9867f56d-2521-4a63-8134-cf194cb4eca6)
http://psobb.xrea.tk/droplist/itemdata/item31012623.html

Weapon Shield Bronze
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/e0600617-fb2c-4fcb-ac68-db6eeb1cd56e)
http://psobb.xrea.tk/droplist/itemdata/item31012633.html


But this only applies to the Event version of the Maximum Attack quest, Maximum Attack v2 is an entirely different quest. 
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/10f54705-db03-49d6-8674-ab74db8ec66a)
Quests 142 and 143

**Comment by Elixir70** [comment]
Cell of MAG 502 is in my list. 

I never added the Weapon Shield flags because they're not in the AOL Cup version that most private BB servers use, and the addon allows users to add/change the flags read and displayed.

It looks like the flag for receiving Chu-Chu, Kapu-Kapu, and Chu-Chu Fever collides with the MA2v2 points. Similar problem for those Weapon Badges and their actions. I didn't check if these collisions happen with regular MA2 (the version without Seabed/Tower) but they probably do because the points aren't specific to the v2 version.

There aren't any fully free global flags for a server that uses all of Sega's quests, which is probably the reason server offer the AOL Cup version (although getting Cell of MAG 502 and going to Ruins will affect MA1 and MA2 master flags, but the rewards in their shops aren't much).

**Comment by fuzziqersoftware** [comment]
The $qfread command has been added.
