### ISSUE TITLE
PSO GC clients unable to connect if pc-login server is disabled

### ISSUE THREAD

**Issue by Gamizard** [fuzziqersoftware/newserv#37]
PSO GC clients are unable to connect if the pc-login server is disabled.

```
I 101659 2022-09-01 23:00:55 - [Server] Client connected: C-1 on fd 21 via 12 (T-9103-PC-gc-us3-pc_console_detect)
W 101659 2022-09-01 23:00:55 - [Server] Error during client initialization: _Map_base::at
```

**Comment by fuzziqersoftware** [comment]
This happens because the initial action on those ports is to send a command that redirects PC clients to one port (pc-login) and GC clients to another, so both ports have to be defined. If you don't want to accept PC connections at all, you can change the behavior for the GC ports from `pc_console_detect` to `login_server`. I'll add a check for this at startup time, and a comment in config.example.json.

**Comment by Gamizard** [comment]
Resolved as of latest changes. Thanks.
