### ISSUE TITLE
[Episode 3] Lobby banners are corrupted for players on hardware

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#380]
**Describe the bug**
Banners are corrupted on hardware in the lobby, they appear to show a very strange flickering texture instead of the intended image. The banners in this case are .bmp images convereted and compressed by newserv itself.

**To reproduce**
1. Place a .bmp image in system/ep3/banners
2. Have newserv convert and compress the image
3. Enter the lobby

**Game version(s) (choose one or more of the following):**
Episode 3

**Video**

https://github.com/fuzziqersoftware/newserv/assets/33199242/1db57259-b8d3-4aae-923a-1946dacb79f2

**Additional context**
Here's the actual image used: 
[Gigobooma.zip](https://github.com/fuzziqersoftware/newserv/files/14218975/Gigobooma.zip) (GitHub doesn't accept .bmp, who knew?)

Here is how it should look, which works perfectly on Dolphin: 
![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/5119c654-6978-4efc-9acb-22104dc97b9f)

**Comment by fuzziqersoftware** [comment]
Unfortunately I can't easily test on real hardware... but maybe a differential approach will work here. All five of [these files](https://github.com/fuzziqersoftware/newserv/files/14490321/banners.zip) work correctly on Dolphin, but I suspect some of them will not work on hardware. If you could test these and let me know which work and which don't, that would help narrow down what the issue is.

**Comment by Matt-Swift** [comment]
Got someone to test this out, all of them work.

However, `hc` and `re` have interesting behaviour in that if they are present, all other banners in the lobby are replaced by them, but this isn't the case for the other 3.

**Comment by Matt-Swift** [comment]
To add, reducing the size of the image from 300x300 to 128x128 makes it work perfectly.

I don't know enough about .gvm images to know why this is the case.

**Comment by fuzziqersoftware** [comment]
It may be the case that GC hardware requires texture dimensions to be a power of 2, which would explain why this works on Dolphin and not on hardware (because modern hardware doesn't have this restriction). If the Gigobooma texture also works when scaled to 256x256 or 512x512, then I think we can be pretty sure this is the cause. I'll update the instructions to mention this restriction.

**Comment by Matt-Swift** [comment]
It works when scaled to 256x256 as well, so this is going to be the cause. I will close this issue.
