### ISSUE TITLE
[Feature Request] Implement the Xbox Beta/NTE

### ISSUE THREAD

**Issue by ShiftaDeband** [fuzziqersoftware/newserv#384]
**Feature Request**
You've managed to implement every known version of PSO from prereleases, NTEs, revisions, and all -- with (potentially) one exception. There's an obscure version of Phantasy Star Online, [the Xbox PSO Episode I&II NTE](https://imgur.com/a/7uAPNRi). [This archive folder](https://archive.org/download/microsoft_xbox_p) may be of interest.

It's time to finish the fight. 

**Game version(s) (choose one or more of the following):**
Xbox NTE, known to SEGA apparently as the 'Phantasy Star Online Episode I&II Beta Version' for Xbox.

**Additional context**
This is pretty straight-forward. Before we get into this, let's set the scene a little bit.

> It's late 2002. The Dreamcast is dead, and the newly released PS2, GameCube, and Xbox are dancing on its grave. PSO Episode I&II just released on the GameCube in Japan and North America. And you're sitting in a restaurant, irritated that they're playing "A Thousand Miles" by Vanessa Carlton for what must be the third time in the hour.
> 
> Overseas in Japan, Microsoft is preparing to launch a beta of the Xbox Live service to 5,000 people (and later, an additional 100 people through a raffle.) 
> 
> The 5,100 people who manage to get in are provided with an Xbox Live Beta Starter Kit. [In this kit, among other things,](https://web.archive.org/web/20021206054109/http://xbox.eg.nttpub.co.jp/news/news128.html) is a special copy of Phantasy Star Online Epsiode I&II - the 'Beta' version. [The service starts its beta on November 21 using this PSO version and a few others](https://web.archive.org/web/20021206081949fw_/http://xbox.eg.nttpub.co.jp/news/news1203_01.html). It's important to note that these players still had to purchase a Hunters License even for the beta.
> 
> Time goes by. The Xbox Live Beta goes well. After ringing in the 2003 New Year, Yuji Naka congratulates a player who gets to level 100 after two months. (seriously, [this happened??](https://web.archive.org/web/20030222055504fw_/http://xbox.eg.nttpub.co.jp/news/news030116_01.html)) 
> 
> On January 16, 2003, Xbox Live is released to the public in Japan, along with a _new_ Xbox Live Starter Kit that contains, among other things, Phantasy Star Online Episode I&II, this time being called the 'product version'.

What's super weird about this version is that almost all of the files on the disc are the same as retail, minus the game's executable (default.xbe), [and not many other files](https://shiftadeband.com/etc/XboxNTE/BetaToFinalJ.html), at least [ones that matter to the server](https://shiftadeband.com/etc/XboxNTE/Differences.zip).

A few key notes:
- The Beta/NTE build's TimeDate is **Sept. 22, 2002**. The Final build's TimeDate is **November 15, 2002**.
- The quests, PR2, PR3, and .GSL files seem to only contain text fixes.
- Word Select files seem to at least match the indexes of final, though the files themselves must be using something like a different terminating symbol or carriage return?
- I have _no_ idea what's going on in ItemPMT.prs.
- The lobby files load fine as they are and I do not understand the differences other than... one is saved with a different encoding format than the other?
- It looks like this version really is full, including the ability to fight Dark Falz and Olga Flow (and other bosses)

Of course, known issues still exist with this version: 
- Without a title update, the bug with Episode 2 Challenge Mode maps will be present.
- The text/font used for things like player names is still mangled.

This is likely (?) an easier addition to newserv with extremely limited payoff. Even with that, I'd argue it'd be pretty cool to see the culmination of all known versions supported. Heck, I'm wondering if there's _any_ change with networking code here at all. (Maybe only in the Xbox authentication?) 

If I could be so bold -- aside from any weirdness or notable changes in ItemPMT.prs -- I wonder if this would just connect to newserv if it was able to authenticate as-is. (Do Xbox versions send any information about their version/title update/anything else to differentiate themselves to the server? I assume no, that's probably done earlier in the Xbox auth/connection process. I suppose the only way to know which version is which is which port Insignia would send the client to?)

With Insignia, you'll be at the mercy of them 1) implementing the ability to connect to the game _at all_ as it is not currently implemented, and 2) connecting to a newserv instance depends on them implementing a way to connect to a custom server. (I did see that request in the Discord a while back and hope that, one day, we may see some kind of custom IP in the user panel.)

I know this may be a longer term request, but I'd rather log it than not. It's crazy to see the progress newserv has made over the course of the project, congratulations!

**Comment by fuzziqersoftware** [comment]
The production versions of PSOX have been tested with newserv already, but Insignia now requires title updates to connect to any server, and I wonder if this will apply to the beta, if they have plans to eventually support it. I've been told that the PSOX beta has been (minimally) tested with newserv by the Insignia developers and that it "just worked", though I don't know if they tested anything in-game or just walked around the lobby, and I wouldn't claim compatibility until I've tested it myself.

I've looked at the file differences. My findings line up pretty well with yours:
- ItemPMT is exactly the same, except a single entry was added to the photon color table after the beta version. This should should have only aesthetic effects.
- The GSL archives don't contain any differences that the server would care about.
- The ws_data files are likely identical. newserv can only parse English ws_data files (the format is different for each language!) but the English files result in the same decoded results.
- TextEnglish contains some [differences](https://github.com/fuzziqersoftware/newserv/files/14231651/TextEnglish.json.diff.txt), but it's mostly just cleanup of bad translations and replacing strings that needed to reference Xbox Live.

This just leaves the executable differences. From a cursory look at the disassembly, I haven't found any notable differences from the final version, but I can't do my own testing because the beta version hangs on startup in xemu. I'll have to ask the Insignia folks for help with this one.

**Comment by ShiftaDeband** [comment]
As for the title update, it wouldn't apply to this version, at least at this time. The Beta's Title ID is `4D530043`, while retail releases (J/U/E) are title ID `4D53004A`. I mean, it could if they're able to modify the title update to the Beta's ID.

As for Xemu, I've been able to boot it up and load games, etc. I did have to make sure the title was remade as an XISO via [extract-xiso](https://github.com/XboxDev/extract-xiso).

**Comment by ShiftaDeband** [comment]
Oh, I totally agree that it's not a priority of any kind on their end -- it's more of a hopeful dream at some point. (Plus, though rare, it did look like some people tried to connect to it in the past.) I wouldn't argue this is a meaningful change, just something that's kind of neat in the grand scheme of things (plus part of Xbox's history, especially with the 2002 beta.)

Would it be correct in assuming you have some kind of higher access there? I have a NTSC-J Xbox, but even on real hardware, it _refuses_ to do anything while bursting and will eventually just crash and/or lock up while connecting. It won't even think about even getting to the lobby screen.

**Comment by Matt-Swift** [comment]
Kinda, for the purpose of newserv testing, I have access to my own server through Insignia, as does fuzziqer.

I wouldn't ask them about this yourselves - as I don't think they would really want to be adding lots of random servers to the Insignia list, even if hidden. I already spoke to one of the Insignia developers however, and they have agreed to grant fuzzi and I access to the beta version of PSO on our servers, though it won't be made public access until the other servers also support it, as they don't want people trying to connect to other servers with unsupported versions.

**Comment by ShiftaDeband** [comment]
Thank you for mentioning the other servers - it was the last thing I meant to mention as well. Of course they'd need to be considered as well, especially for compatibility.

I really appreciate your thoughts and time here. Thank you!

**Comment by nolrinale** [comment]
Insignia is for now a private project but I'm sure @LukeUsher can provide us a way to connect with our newserv instances  to their Xbox Live gateway and test PSOX maybe by setting our Insignia accounts with a special DEV profile or something like that.

**Comment by Matt-Swift** [comment]
The Xbox Beta has been tested on newserv, per fuzziqer's update in https://github.com/fuzziqersoftware/newserv/commit/af8c27dcefe585b6661f1191b3b752afd28ad36c

Insignia helped out with this one, from what I'm able to tell it just works although it has a funny auto disconnect bug where it doesn't respect the setting. (client-sided bug)

**Comment by nolrinale** [comment]
Then if thats the case I think this ticket shall be closed too as it has been implemented already

**Comment by fuzziqersoftware** [comment]
Yes, this has been tested. I played a crossplay game with a GC player and loaded a quest and I didn't notice anything unusual. Aside from the idle disconnect timeout bug, the beta version seems to be the same as the final version. I still intend to get the command tables and quest opcode table from the beta version and check them against the final version before calling this complete though.

**Comment by fuzziqersoftware** [comment]
I've now looked over the tables, and it looks like this version is indeed very similar to the final version - the tables match the final version's tables, including the F94D quest opcode which has a special meaning on the Xbox versions of PSO. The server recognizes the beta as a distinct version for the purpose of patching (specific_version is 4OJB), but it otherwise treats the beta as if it were normal PSOX, and everything seems to work.

100% compatibility is a goal of this project, but I also just enjoy seeing what changed during the game's development. Here's hoping some new previously-unseen betas / prototypes are unearthed sometime soon for us to add support for :)
