### ISSUE TITLE
[BB] get_physical_data op code doesn't work correctly

### ISSUE THREAD

**Issue by toiletman74** [fuzziqersoftware/newserv#399]
**Describe the bug**
The get_physical_data op code doesn't work right. Instead of changing an enemy's stats it has weird effects such as making enemies invisible or making them untargetable.

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Download and install the psobb monster reader addon from [here](https://github.com/Solybum/PSOBBMod-Addons).
2. Make sure the target window is enabled in the addon.
3. Download and load up [this quest](https://drive.google.com/file/d/1NqK8pvlypAasHs66PZjNIJyVpIZuWAV0/view?usp=sharing). (or any quest that uses the get_physical_data op code)
4. Talk to the NPC that you spawn in front of. (She runs the get_physical_data op code. It should change the booma's stats to what they are on ultimate.)
5. Go to forest 1 and using the monster reader's target window check the booma's stats to see that they haven't changed.

**Game version(s) (choose one or more of the following):**
BB

**Server log output**
[current.txt](https://github.com/fuzziqersoftware/newserv/files/14355549/current.txt) <- log. At the end of the file I loaded the quest and talked to the NPC which changes the booma's stats to what they are on ultimate.

**Comment by toiletman74** [comment]
huh, maybe it is just a problem with the teth client.  I did also test a quest from ultima that uses the get_physical_data command and it didn't work either though on the teth client

**Comment by Elixir70** [comment]
The client changes this data in memory and doesn't tell the server. So it's not an issue in newserv at all.

But this opcode works fine on the Teth client. The Ultima client is the Teth client. I don't know what quest from Ultima you're referencing, but I know some of those do changes only in ultimate difficulty, and a few others don't even change the BPs until special waves near the end of the quest.

Your quest has a bunch of issues which is why it's not working.

You're talking to the NPC on P2 and then you're changing floor. For BB, changing floor resets any BP changes. You need to change them when you're on the floor.

The argument for load_enemy_data is wrong. Booma is 0x4B and not 0x4A. Qedit has most of these identified correctly, but there are still some wrong ones for the other BP tables (because a single monster need not use the same index in each table). Esc listed them all out for his omnispawns patch a few years ago: https://github.com/Solybum/Blue-Burst-Patch-Project/blob/2c953645ecc570437f720e5461dc0c5ecf414928/Blue%20Burst%20Patch%20Project/battleparam.h#L79

Your Booma is on wave 0. Even if you fixed the above issues and put the BP change opcodes in the floor handler, it still won't work because the Booma object in memory is created before the floor handler runs. (This is yet another reason why wave 0 in quests can be problematic if you're doing anything with them that depends on scripting). Put the Booma on a wave called by a map event (with a nonzero delay because those are also problematic for a bunch of reasons), and as long as your quest script runs before the map event is called, the changes will work.

Also your quest has an undefined label used for the floor 1 handler. Calling/executing script for undefined labels is a very easy way to make players crash randomly.

**Comment by Elixir70** [comment]
I don't have any real quests that use these opcodes that I can share. But here's the quest you posted with it working.

[test1.zip](https://github.com/fuzziqersoftware/newserv/files/14369966/test1.zip)

**Comment by toiletman74** [comment]
Finally got around to testing that quest you sent and it works fine
