### ISSUE TITLE
[Blue Burst] [Feature Request] PSOBB Hangame Gateway Service

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#401]
This is yet another hidden feature of PSOBB that is barely documented and tested, but figured would be interesting for you guys to check about it now that we are talking about NTEs and Beta Versions

PSOBB had another way to connect to the official servers in Japan via the Hangame gateway, this service was created as a last effort to bring more players to PSOBB which at the time they released this (back in april 2008) the game population was starting to dwindle a lot so they came up with a way to diversify and offer the game via this portal too.

Sega offered a custom client for Hangame but it was actually very similar to we had in the main version but allowed the launcher to start differently so users of the Hangame portal could launch the game from the huge GAME START button at the homepage

Players with Hangame licenses accessed the same server we were playing on and our same ships, they didnt had any extra  ship or anything of that sort not even a unique name color. It was just like a gateway service using different login credentials.

I write all this because I noticed in the file https://github.com/fuzziqersoftware/newserv/blob/4e4ba5650dad5b2569bd6a1d30d184bfafd79d52/src/CommandFormats.hh
there are many undocumented parameters regarding the login process in some of the BB functions, figured they might be the ones related to how they attached Hangame login to the original system.

(This is one of the reasons why I also mentioned in the client topic that there's more than meets the eye in launch.exe as well)

Here's the official gateway site for Hangame users
https://web.archive.org/web/20081221233615/http://psobb.hangame.co.jp/

And the press release at the time
https://linecorp.com/press/files/PRESS_20080415164151.pdf
https://game.watch.impress.co.jp/docs/20080415/psobb.htm
https://www.4gamer.net/games/012/G001294/20080415020/

**Comment by nolrinale** [comment]
This one is not necessary for newserv but for research purposes to fill the gaps in packet definitions

**Comment by fuzziqersoftware** [comment]
There is an option in 1.25.11 and 1.25.13 (including the Tethealla version) to enable the Hangame flag, and it seems there are meaningful behavior differences when the flag is enabled. I'll investigate these and document them soon.

**Comment by fuzziqersoftware** [comment]
The Hangame flag in the client does a few things, but it does not meaningfully affect gameplay.

Normally, when psobb.exe is run, the launcher passes either 'SEGA' or 'AGES' encoded as a 32-bit decimal number as a command-line argument, and the game either launches normally or plays the intro video depending on which value is given. There is a third value, 'GN@H' (presumably meant to be 'H@NG' but in little-endian order), which enables Hangame login mode. In this mode, the username, password, and a third unused string are encoded in an extra command-line argument. The login string is checksummed and encoded based on the current time; the string is only valid for 1 hour after it's generated. The function `encode_psobb_hangame_credentials` in SaveFileFormats.cc can be used to encode credentials in a way that the game will accept.

In Hangame mode, the following behaviors are different:
* The username must end with '@HG', and may be up to 11 characters in length.
* The password must be numeric, and must be between 1 and 8 characters in length.
* The username and password aren't saved to the WIndows registry.
* The client doesn't show the patch server or login credentials items in the main menu; the player only sees "Start Game" and "Exit Game".
* The length limits in the username/password entry window are different. This appears to be unused functionality, since that window seems to be inaccessible.
* The patch server domain name and port are different. (The port is 11200, which has been added to config.example.json.)
* The data server domain name is different, but it still uses port 12000.
* Episode 4 is always unlocked, regardless of the flag sent by the server during login.
* The client refuses to connect to any data server because it thinks its version number is incorrect. The patch 0048210D EB bypasses this check on TethVer12513.

This was a fun exercise in reverse-engineering, but unfortunately the differences turned out to be fairly mundane.

**Comment by ShiftaDeband** [comment]
Just wanted to say thank you both for exploring and documenting this functionality. This is yet another great example of how great this project is, even if this turned out to be mundane -- this is all super fascinating and really cool to see.

Just passing along another thank you.
