### ISSUE TITLE
[newserv] [Feature Request] Extend $persist

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#408]
**Is your feature request related to a problem? Please describe.**
$persist is a very cool feature, however judging from a conversation in Discord earlier today, it isn't doing everything that a user would intuitively infer.

**Describe the solution you'd like**
Couldn't advise what is possible myself, so it would be nice to see if $persist can also hold:
1. The unlocked map state for free adventure (is it possible to remember the sublevels e.g. Cave 2? I'm guessing not)
2. The state of the maps as they were left (e.g. halfway through Cave 1, leave, halfway through Cave 1 is still done)

**Game version(s) (choose one or more of the following):**
DC NTE, DC prototype, DC v1, DC v2, PC, GC Ep1&2, GC Ep3, Xbox, BB

**Additional context**
To add on to this, if the server is able to remember map unlocks in a game, would it be possible for the server to unlock free adventure maps for players who don't have them available online?

Thanks in advance as always.

**Comment by fuzziqersoftware** [comment]
This turns out to be a lot more work than I expected, but I do intend to get to it at some point.

There are five kinds of state that should be synced:
* Enemy state (6x6B). This is fairly easy; clients update flags and damage with 6x0A commands, and the server can track these and update its view of the state.
* Object state (6x6C). This is analogous to enemy state; we can track changes made via 6x0B commands.
* Item state (6x6D). We already support this.
* Set events (6x6E). This is the hard part; within this command, there are several different types of data, and tracking these isn't as easy as watching for update commands from the client. There are commands that update these set flags, but these commands also call virtual functions on the enemy or object, and those functions can update the flags again without sending any command, so the server would need to implement logic for each object and enemy type individually.
* Quest flags (6x6F). This isn't hard but is still nontrivial; we don't actually get this data unless someone else joins the game after the player who created it. After that, we can just track changes from 6x75 commands.

I have a prototype of this on a branch, but none of the per-object/per-enemy logic is implemented, so it doesn't work very well. Boxes broken before a persistence gap will stay broken after a player rejoins (and their items will still be there), but switches are reset to their initial states, and enemies that were defeated before will appear again (but will not drop any items if defeated again).

I'll update here as I make progress on this, but it might be a while before it's working well.

**Comment by fuzziqersoftware** [comment]
I believe this is in a good state, but I won't close this until others have tested it.

The server now tracks all of the above-mentioned data types, and from my testing so far, everything seems to work. Enemy waves that were defeated stay defeated when the room is rejoined, switches and locked doors retain their states, etc. The only thing mentioned in the original request that isn't implemented is preserving unlocked areas; it seems this is normally done through quest flags, but there are only quest flags for 3 of the 10 areas (C1/M1/R1), and the other areas can't be unlocked this way.

**Comment by Matt-Swift** [comment]
I'll give this a try sometime and let you know. A small question though - would it be possible for the server to send those quest flags by default in games even if players don't have them unlocked? My thought process here is that it would be nice if a server could unlock things online without required offline progress.

**Comment by fuzziqersoftware** [comment]
It's definitely possible for the server to unlock M1/C1/R1 in new games; I tried this last night and it seems to work. I'll find the correct flags for the Ep2 and Ep4 areas and add a config option for this.

**Comment by fuzziqersoftware** [comment]
The config option has been added I've tested it in both episodes in GC and it seems to work. Disassembly shows that the flags are the same for v2, so I expect it will work on DC and PC as well.

**Comment by fuzziqersoftware** [comment]
I've been playing with this for a while and it seems stable. If you notice any issues with it, feel free to open a new issue.
