### ISSUE TITLE
Caching patch server file metadata serverside

### ISSUE THREAD

**Issue by rumatsuki** [fuzziqersoftware/newserv#42]
As of right now it seems that every time newserv starts it needs to reprocess the entire patch server data directory (which usually hasn't changed), making it take around a minute for the server to start. It would be great if it could cache the contents of the folder so startup doesn't take as long on subsequent runs.

**Comment by fuzziqersoftware** [comment]
Are you using the latest version of phosg? I updated phosg's crc32 function today to make it quite a bit faster for exactly this reason. I also considered implementing a metadata cache in newserv; if it's still too slow to start with the latest phosg version, let me know on this ticket and I'll figure out some solution.

**Comment by Gamizard** [comment]
I'm using the latest version of it, yes. The problem is most likely a weak processor as I'm currently running newserv on a VPS.

**Comment by fuzziqersoftware** [comment]
I've added a checksum cache which hopefully will make startup faster (after the first time). Beware, though: this adds a new potential source of bugs since patch files now may not be loaded until they're actually needed by a patch client. So, it's now inadvisable to modify the patch files while the server is running.
