### ISSUE TITLE
[Question] Server side drop rate multiplier

### ISSUE THREAD

**Issue by mattbbx1** [fuzziqersoftware/newserv#423]
Is it possible to have a blanket rare item droprate multiplier instead of modifying the table of all rare items independently? 

**Describe the solution you'd like**
Add a simple multiplier function to all rare item droprates. 

**Game version(s) (choose one or more of the following):**
DC NTE, DC prototype, DC v1, DC v2, PC, GC Ep1&2, GC Ep3, Xbox, BB

**Additional context**
Not much else to say, just wasn't sure if I missed this in the documentation.

**Comment by nolrinale** [comment]
for BB is there already in the config.example.json if you scroll all the way down, now if you want to adjust the rates for the other versions I think it requires some patching at the client level.

**Comment by fuzziqersoftware** [comment]
There is an EXP multiplier in config.json, but not a drop rate multiplier. This is because the game has a built-in command that allows the server to set the EXP multiplier, which is needed for the client to show the correct EXP numbers if the EXP rate isn't the default.

I think this functionality makes more sense as a CLI command rather than a config option; you could then run (for example) `newserv multiply-drop-rates rare-table-v4.json rare-table-boosted-rates-v4.json 1.5` to get a new drop table with higher rates, which you could then put in system/item-tables/. I'll implement this CLI command soon.

**Comment by fuzziqersoftware** [comment]
This has been added. To generate a new item table with modified rates, you can use (for example) `newserv convert-rare-item-set --bb system/item-tables/rare-table-v4.json system/item-tables/rare-table-modified-v4.json --multiply=2`. You can then rename rare-table-v4.json to rare-table-v4-orig.json and rare-table-modified-v4.json to rare-table-v4.json to use the new table.

**Comment by mattbbx1** [comment]
Thanks so much for implementing this!

**Comment by ryu777mtg** [comment]
When do you issue the command above?
I'm using a LInux Server and when inside folder using ./newserv will start the server using help does not show that command
When trying to utilize the command in or outside of server cli I get errors.

Inside of newserv cli I get the following `FAILED: no such command; try 'help'`

Ouside of neserv cli which would be Linux cli I get the following `terminate called after throwing an instance of 'std::logic_error'
  what():  configuration filename is missing
Aborted (core dumped)`

Most likely doing something completely wrong here on my end

**Comment by fuzziqersoftware** [comment]
Some of the less-common CLI commands were broken during a recent refactor. I'll push a fix shortly.

**Comment by fuzziqersoftware** [comment]
In the meantime, it probably will work if you also give `--config=system/config.json` (this wasn't required before, and it shouldn't have been - this will be fixed soon)

**Comment by ryu777mtg** [comment]
From your command above is the `--bb` for Blue Burst and would that need to be changed to say `--gc` for Gamecube etc just didn't really see to much documentation on it.

Thanks and no hurry just noticed it didn't work when attempting it

**Comment by fuzziqersoftware** [comment]
Yes, you would use `--gc` if you were working with GameCube drop tables. If you run `newserv help`, it will tell you about the version options at the end of the help text.

**Comment by ryu777mtg** [comment]
Is their a max increase to the global multiplier value? Curious just trying to see any sort of change haven't notice anything or is their something that needs to be done to apply the table after the rename?

Maybe I'm doing something wrong but it does create a new table. Maybe I just don't understand these item-tables but I ran the command `sudo ./newserv convert-rare-item-set --gc system/item-tables/rare-table-v3.json system/item-tables/rare-table-modified-v3.json --multiply=100`, As I assume GC 1&2 is v3. Rename the old to .orig and the new to the old file name. Run newserv join and looking for some sort of change to no avail nothing actually seems to be working.

I did notice the new file created also has executable permissions added in linux.

I have also tried this option in the config.json
`"ServerGlobalDropRateMultiplier": 100.0,`

I'd at least thought to expect some sort of increase but maybe it does it to all items scaling everything so nothing actually changes.

Sorry just trying to get a better grasp on the actual command and how it works as I was hoping to combine it with maybe cron to have it run a scheduled task to change server item rate at specified intervals and back.

**Comment by fuzziqersoftware** [comment]
There is no maximum or minimum multiplier, but the probabilities are clamped to [0, 1], so if you e.g. multiply by 100000 and then divide by 100000, many of the probabilities will end up as 1/100000 (since they were clamped to 1 after the first multiplication).

Which drop mode are you using? By default, all versions except BB use client drops, so changing the server's drop table has no effect. To use the server drop tables on non-BB versions, use `$dropmode shared` in the game. You can also change the default drop mode in config.json (see the `DefaultDropMode` options).
