### ISSUE TITLE
[Blue Burst] [Feature Request] Add the missing multiplier for Drops and Team Points

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#426]
**Is your feature request related to a problem? Please describe.**
The global EXP multiplier is already added for PSOBB but BB also supported the following ones:

- A multiplier to increase the chances of dropping more rare items
- A multiplier to increase the value of the items exchanged for team points

Something like this added to the config.json
```
"BBGlobalEXPMultiplier": 1,
"BBGlobalDropRateMultiplier": 1,
"BBGlobalTeamPointsMultiplier": 1,
```

**Comment by fuzziqersoftware** [comment]
The global EXP multiplier exists because that feature exists natively in the client (there is a command that tells the client to multiply all displayed EXP values by a factor). There is no client command for the drop rate multiplier, but since drop rates are never shown to the player, we could still add this on the server side. For team points, however, there doesn't appear to be any function in the client that causes it to show all values multiplied by a factor, so the only way to reliably do this (and have the client show the correct values) would be to preprocess the ItemPMT tables and send the modified tables to the client. This would be very tedious; even if I implement an ItemPMT encoder in the future, there won't be an option in the config to do this automatically.

I'll leave this open to track the drop rate change.

**Comment by nolrinale** [comment]
Just letting you know this is stuff sega used all the time in BB for several events

**Comment by fuzziqersoftware** [comment]
The drop rate multiplier has been added.

Re: team points, there is no easy way to do this because it involves re-encoding the ItemPMT file. I've added a TODO to write serialization functions for various tables, including ItemPMT, but I will not work on this soon.

Re: rare enemy rates, there are only 8 fields (and 7 of them are the same by default) so it doesn't seem worth the effort to add a global multiplier too - you can just change the 8 values in the dictionary.
