### ISSUE TITLE
in-game drop announcements

### ISSUE THREAD

**Issue by coffeemate77** [fuzziqersoftware/newserv#450]
a nice feature to have here is knowing when ur teammates get something cool, how cool it is, and immediately via the server instead of awkwardly typing. kinda like psp2
ie 
PLAYER
10* HITOGATA
0/0/0/0/0

i wish scrolling text was a thing. it would look cool here

support anywhere youd get actual drops, so probably v1, v2, GC/Xbox, BB
thank you :3 
![Screenshot_20240327-091058](https://github.com/fuzziqersoftware/newserv/assets/114520807/dd41333f-f521-426b-b735-cd6cc7a0e9f0)
attached is an ugly screenshot of what im getting at

**Comment by nolrinale** [comment]
This function already exists via the `$itemnotif` command, or additionally you can enable it server wide by default by adjusting the values in the config.json 

```
  "RareNotificationsEnabledByDefaultV1V2": false,
  "RareNotificationsEnabledByDefaultV3V4": false,
```

lets close this ticket

**Comment by fuzziqersoftware** [comment]
This request is about notifying other players when one player picks up a rare item, which is not covered by the existing rare notifications, since the existing notifications tell you when an item is dropped and are only visible to players who can see the item. I intend to add the requested feature soon.

**Comment by Matt-Swift** [comment]
I see that this has been implemented, but just wanted to make a suggestion;

You've added global rare notifications (which is very cool), however a 12* min roll only applies to very few items that drop (on V3, this is Heaven Punisher and Psycho Wand only). Making this 11* min roll on the regular table is kind of obscene though, as you'll find out when people get things like God/Units.

This is actually how it worked on the official BB servers (that is, an 11* check), but I wonder if it would make more sense to be able to define a list of items instead of a rarity check for the globals? Certain items such as Handgun:Guld or Sealed J-Sword are missed off for example, and on BB you don't see Lame d'Argent drops either since that is 10*.

**Comment by nolrinale** [comment]
Related to this feature
https://github.com/fuzziqersoftware/newserv/issues/354

**Comment by fuzziqersoftware** [comment]
This has been changed to use an explicit list of items for both game-wide and server-wide notifications. (And unlike before, the default is blank, so this feature is now disabled by default.)
