### ISSUE TITLE
[Blue Burst] Flag UnlockAllAreas=false, but all areas are unlocked

### ISSUE THREAD

**Issue by RaikohKatsushiro** [fuzziqersoftware/newserv#452]
Flag UnlockAllAreas has been always set to false in config.json, but all areas are unlocked from the start in PSO BB. This applies to both _one person_ and _normal_ modes, for all episodes.

Is this intended? If so, what is this flag's intended behavior?

Thanks!

**Comment by nolrinale** [comment]
Yes this is intended in PSOBB it is the correct behavior of the client, however the story progress is still being tracked by clearing the Government Quests as usual and you require to clear them in order to gain access to the Side Stories in Solo EP1. PSOBB initially didn't had the areas opened by default either but SEGA decided to patch it internally in the game client to be opened by default to encourage people to level up a little bit faster and make your game a little bit easier. 

This setting is mostly useful for PSOGC and older versions of the game.

**Comment by fuzziqersoftware** [comment]
I don't know exactly when Sega made this change, but the Tethealla client is based on a version that opens the areas by default, so this setting does nothing for players using that client. newserv also supports older versions of the client which don't have this behavior, and this setting would affect those versions if you use them.

I've added a comment in config.example.json to clarify the BB behavior.

**Comment by RaikohKatsushiro** [comment]
Understood, thanks. @fuzziqersoftware A question though: that Tethealla installer that you're linking in the README has 2 versions we can choose from: 12510 and 12513. Do you know if 12510 would be that other version without areas unlocked? Is there documentation somewhere that explains any significant differences between these 2 clients?

**Comment by nolrinale** [comment]
12510 and 12513 are actually 1.25.10 and 1.25.13 with this one being the final one at the time of PSOBB end of service at December 27th 2010.

The last patch that actually added/changed stuff in-game was 1.25.9 and those changes were only a few tweaks to the rare item announcement system so it would be less spammy. 

Sega released the final client for download which is version 1.25.11 (which is the one we have archived) at this point there was a total feature freeze and no other changes to the game were made which lasted most of 2009 and 2010

In the last months before the end of service they had issued 2 small patches which increased the versions to 1.25.12 and .13 respectively these patches only focused on fixing an issue with the Gameguard not launching properly and not allowing people to play during the last months of the game think of it as a last minute fix to keep the game running for longer. 

The patch that actually added all the areas opened by default happened during the 1.24.X series back in 2007 when they added the improved drop tables including the special items dropped by Episode 1 and Episode 2 bosses. In order to encourage people to hunt for these with ease this is the reason why they enabled all the areas by default (and by that date the population of the game was heavily dwinling a lot too leaving us with only 6 active ships from our initial 12 ships) 

Once we settle the situation with the 1.25.11 client in the other ticket and is easily installable I will prepare a PR to the readme to also offer this via to install PSOBB without relying on the modded Tethealla client.

**Comment by RaikohKatsushiro** [comment]
That was a very interesting read, thanks! I played a lot on the Dreamcast days (V1 and V2), and a bit on the Gamecube, but mostly skipped the PSO BB era while the official servers were up, so it's interesting to learn more about it :)

When that ticket regarding 1.25.11 is solved, will we then be able to easily connect to newserv using that version (or a modified, unpacked, etc. version of that one)? Just curious about the final outcome on that one, versus what we have now with the Tethealla clients.

**Comment by nolrinale** [comment]
Ideally making 1.25.11 from the official client work with newserv would mean that everyone share a single installer (the official untouched sega one) and thus avoiding more confusion regarding which client to use for a basic installation and avoid all the confusions you had to go through while setting up the game, file conflicts, patch server setup, etc. 

Tethealla while it appears to be mostly untouched its actually heavily modified inside in different points which at the time was made with the effort to make the game at least run and connect to a private server, its not obvious to a person that havent played PSOBB but I was actually a former JPBB player and could tell stuff were odd here and there. 

But for the time being it's still being figured out how to adapt 1.25.11 to run without many headaches for the final user in the other ticket

**Comment by RaikohKatsushiro** [comment]
Gotcha, that would be wonderful, thanks for the effort! :)

One last curiosity of mine on this topic: I noticed the opening movie in PSO BB (after you just created a character) is some slideshow-looking thing. Was this the same as in the official PSO BB back in the day, or also got modified/updated at some point? Asking because it looks far inferior to the Gamecube version, and I wonder what was the purpose there.

**Comment by nolrinale** [comment]
PSOBB despite is based on the XBOX version had to do some compromises to work on the computers at the time by removing certain refraction effects the consoles could pull and also the limitations on internet speeds and hard disk we all had, so they removed stuff like the FMV and created the slideshow intro to make the client lighter to save up on bandwith costs and also players able to download the game with much more slower speeds.

The recommended speed to play the game was 256kbps but I was able to play with people that managed to play with a 56kbps modem connection so downloading 500ish MB (with more data later needed to be downloaded for EP4) was kinda a big deal back then.

On top of we all having horrible computers to play the game, for example I could only run it on the lowest graphic setting as I was playing with a NVIDIA TNT2 with 32MB of VRAM and was struggling very hardcore, but several people were playing with Vantas, or S3 graphics very ancient stuff that ran the game even worse.

It all might sound alien now as the game can run in pretty much everything these days but 20 years ago it was a completely different story.
