### ISSUE TITLE
[Blue Burst] Some quests use English versions, others use Japanese version

### ISSUE THREAD

**Issue by RaikohKatsushiro** [fuzziqersoftware/newserv#453]
**Bug:**
Some quests in PSO BB are using their Japanese counterpart (i.e. displaying a Japanese name and description), but not all. For example, Episode 1 One Person mode "Story" quests are all in Japanese. But most of the "Retrieval" quests in Normal mode, as well as all the government quests so far, are in English.

**newserv logs:**
I noticed that for some of these quests, both E and J versions seem to be loaded, but the Japanese version is the one used. Example with quest Magnitude of Metal:
```
I 701 2024-03-31 00:37:58 - [StaticGameData] (q001-bb-e.bin/q001-bb.dat/q001.json) Created BB_V4 E quest 1 (Magnitude of Metal) (Episode 1, Story (11), not joinable)
I 701 2024-03-31 00:37:58 - [StaticGameData] (q001-bb-j.bin/q001-bb.dat/q001.json) Added BB_V4 J version of quest 1 (鋼の心)
```

**Extra info:**
This may be related to [my previous issue](https://github.com/fuzziqersoftware/newserv/issues/448) on setting up patch directory data. Although I managed to get the server to run properly and the client to connect successfully, could something with the data be off still?

I also noticed that the symbol chat names are in Japanese, in case it's related (the remaining UI is entirely in English).

Running the latest newserv build on Windows 10.

Thanks!

**Comment by nolrinale** [comment]
Because you decided to use the Tethealla client, by default the Tethealla client is a heavily modded Japanese client which by force changed a few files to partially enable english text. 

So effectively you are running the japanese client and thats why newserv displays your quests in japanese if they are available in that language, if you delete all the data folder of that client and use the data folder of the untouched japanese client i shared with you before you will load all the game correctly in Japanese (the default for PSOBB).

In order to actually set the game in english (entirely) you are required to change the language flag of the client and provide the extra localized files, you can find all the information and files needed about this procedure in the `notes` folder.

After completing this step your client will properly load the correct english strings and your character data will also be set to english language upon creation for stuff like the symbol art names, word select, guild card, etc.

**Comment by RaikohKatsushiro** [comment]
Is there no way to use the [Tethealla client linked in the README](https://github.com/fuzziqersoftware/newserv?tab=readme-ov-file#pso-bb) without the need of getting additional clients/data or hex-editing the .exe? Just wondering as it'd be super helpful in getting friends or other generally less tech-savvy PSO fans to easily play PSO BB using this server. And yes, I understand there are private servers around there that make playing the game seamless, but I feel it's also important for matters of preservation as this is an extraordinarily complete and open-source project.

With that said, I followed the steps you suggested, got the JP files, added the US files on top and then hex-edited the .exe to switch it to English according to the `notes`, as well as [KrisanThyme's helpful tips](https://github.com/fuzziqersoftware/newserv/issues/448#issuecomment-2021021129). Unfortunately, the issue remains exactly the same as I described it, except that now I have access to all Story quests from the start instead of just the starting 3, as I would prefer. See screenshot:
![pso1711907034](https://github.com/fuzziqersoftware/newserv/assets/115497799/c1061057-adf8-41a0-ac41-b15118684d03)

Again, only **some** quests (and default Symbol Chat options) is in Japanese. Everything else is in English. Where could I have made a mistake here? Any other ideas?

**Comment by Matt-Swift** [comment]
It's a bug in newserv, as using a client that starts with TethVer is meant to force English language, per here: https://github.com/fuzziqersoftware/newserv/blob/acbebaeb70ebabe2964cf0516c15af84953532e2/src/ReceiveCommands.cc#L1207

You can just remove the Japanese quests if your server is for English users only, just go to the quests folder and remove any file with -j at the end.

The reason only those show up in Japanese is because I haven't submitted the rest of the Japanese quest files yet.

**Comment by nolrinale** [comment]
Yes this is because despite your client now is in proper english your character was created when the client was still in japanese mode if you recreate your character now with this client your data will be all initialized in english including the quest list.

**Comment by RaikohKatsushiro** [comment]
I wish there was a single variable I could tweak somewhere to force quest language to English, but I guess it's never that simple :') (but do let me know if there is!)

@Matt-Swift As you suggested, removing JP quest files makes these quests default to English. Not ideal, as I wouldn't want to do this for every new release, but serviceable for the moment, thanks!

@nolrinale You're right, when I create a new character, the quests are in English (tested this before removing JP quests as per Matt's suggestion). How can I change an existing character's language?

**Comment by fuzziqersoftware** [comment]
I've added the `$edit language` command just now in the latest commit; to change your BB character to English, use `$edit language E` in the lobby. If you're using the release version, you'll have to build it from source to get this update, or wait for a new release.

**Comment by RaikohKatsushiro** [comment]
I'd like to try building the server from source at some point, but for now I'll just wait for a new release, thanks :)
I did try to edit the .psochar file manually, changing some instances of 'J' to 'E' but obviously I just corrupted it. Though, I assume that's the file that the new command will edit.

On another related question, when I edited the client to be in proper English, all the solo quests became available from the start. What causes this? Just looking to have the client in proper English, but also retain the solo quest progression as normal.

**Comment by nolrinale** [comment]
This one should be entirely fixed with all the latest improvements being made to the server lately

**Comment by fuzziqersoftware** [comment]
Yes, I think all of these issues have been fixed recently; the solo quest progression should be working regardless of the language setting.

Re: whether it's possible to view player data in a human-readable format, there are some tools out there (search for "Ephinea character viewer", maybe) but I don't know if they're good or not.
