### ISSUE TITLE
GC: Added PC automatic version detection appears to break GC login

### ISSUE THREAD

**Issue by clint-david** [fuzziqersoftware/newserv#46]
Updated server to 830a151, and the gamecube version (using port 9100) of the game won't correctly connect.

Using a vanilla config.json the game will find the server and then try to connect to the lobby join screen, but then immediately hangs-up for a minute or so then gives error 100 (game disconnected).

On the server side it sends: 
`newserv> I 8 2022-10-06 21:22:00 - [Server] Client connected: C-1 on fd 35 via 12 (T-9100-PC-gc-us10-pc_console_detect)
[33;1mI 8 2022-10-06 21:22:00 - [Commands] Sending to C-1 (version=PC command=19 flag=00)` 

and then immediately after:
`[0mW 8 2022-10-06 21:22:00 - [Server] Client caused error 104 (Connection reset by peer)
I 8 2022-10-06 21:22:00 - [Server] Client disconnected`

If I change port 9100 in config.json to "gc" and "login-server" I am able to get to the lobby join screen and select "join lobby" but then get a similar disconnect.

I can do some more testing to help diagnose, but kinda unsure of what to try with this one.

**Comment by fuzziqersoftware** [comment]
One possibility is that the GameCube can't connect to the appropriate port on the server side... the lobby server port numbers were changed recently and if you're not running newserv on the same network as the GC, then some NAT config or security group rules might need to be changed (or the ports in config.json could be changed).

Can you share the full console output from newserv, and the port configuration from config.json? Also, which PSO GC version are you using? Hopefully from that information we can diagnose the problem here.

**Comment by clint-david** [comment]
Yep you nailed it. Not sure how but I completely missed that the newserv ports had changed in config.json.

I changed my NAT and worked right away. Sorry about that; thank you! :)

For reference using PSO GC v1.1 (US).
