### ISSUE TITLE
Server cannot load quests when 0x80 flag is enabled

### ISSUE THREAD

**Issue by completereboot** [fuzziqersoftware/newserv#485]
When changing the quest flag in the config.json to: 0x80, the game cannot seem to load any quests at the quest counter. This seems to happen no matter which quest time I activate this flag for. 

**To reproduce**
1. Change the quest flags in the config.json to 0x80.
2. Load into the server and walk to the quest counter that the quest should show up at
3. The quest counter NPC will tell you it could not download any quests.

**Game version(s) (choose one or more of the following):**
BB

**Additional context**
I tried this with all the quest types. Should only be to change the flag value to 0x80? Or have I missed something?

**Comment by Matt-Swift** [comment]
This is because by setting the flag to 0x80 alone, you have not actually defined what mode you want the quests to appear in. The flags field is a bitmask field. I assume you're probably doing this for normal mode quests, so it should be 0x81.

What you need to do is add up all the fields that you want for the quest. For example:

0x081 = Appears in normal mode, and hides quests that don't match the episode. (0x80 + 0x01)
0x124 = Is an Episode 2 challenge category that appears in challenge mode and also appears in the download quest menu (0x100 + 0x20 + 0x04) (you probably shouldn't do this)

**Comment by completereboot** [comment]
> This is because by setting the flag to 0x80 alone, you have not actually defined what mode you want the quests to appear in. The flags field is a bitmask field. I assume you're probably doing this for normal mode quests, so it should be 0x81.
> 
> What you need to do is add up all the fields that you want for the quest. For example:
> 
> 0x081 = Appears in normal mode, and hides quests that don't match the episode. (0x80 + 0x01) 0x124 = Is an Episode 2 challenge category that appears in challenge mode and also appears in the download quest menu (0x100 + 0x20 + 0x04) (you probably shouldn't do this)

Thank you for your help, I appreciate it. :)
