### ISSUE TITLE
[Blue Burst] Quest initialization and sorting issues in latest commit 

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#489]
**Describe the bug**

Couple of Quests Bugs in the latest commit: 

- It is a regression of a previous issue, with the latest commit only the non-joinable Gov quests are being displayed in Japanese
- EP1 Retrieval Quest Sorting is wrong for BB, Lost Hell Pallash is in the wrong place shall be next to the other Lost series 
- Rappys Holiday (137) & Gallon's Treachery (138) shall be placed under the Retrieval Quest categorie for EP1 Hunter Guild
- Valentine Quest (124) shall be placed under the Event category but this other Event category should appear in EP1 one-person mode only as its a single player quest.

**Game version(s) (choose one or more of the following):**
BB

Current incorrect EP1 Retrieval Quest Sorting for BB
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/1f504863-b46c-4c15-9570-2ec944ee796e)

Correct EP1 Retrieval Quest sorting
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/e6473c1a-5f3c-4def-af54-548d8cef4172)

EP1 Retrieval Quests in wrong Event Category
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/a9443d6d-4e2e-44de-9e7c-35cd24b58855)

Gov Quest Language Bug Issue
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/5ec74754-b11e-4b88-8d96-a863b4941fd7)

**Comment by Matt-Swift** [comment]
The quest sorting issues are for you to resolve rather than newserv itself, as newserv (in most cases) has quests numbered by an internal number of one of the versions (which don't always line up), which may not always match the original sort order. To resolve it, simply change the quest file name in your quests folder to be the order you want. (this is why my screenshot which you have posted shows in the "correct order", I have the 4 lost quests as 58-61 in order, even if this wasn't the original internal number for Lost Hell Pallasch).

The actual number that the server uses is not important for BB as it's only really important for download quests, so you can move BB quests wherever you like - it's just that the main newserv repo should have every version have the same quest number for the same quests to not use up unnecessary numbers and so it's also more obvious to people that different numbers are different quests.

This is the same for Gallon's Treachery in the Event folder - you would just move this yourself. That being said if it was definitely there on vanilla and shouldn't be in events (I actually have no idea), it can of course be moved in the default sorting in newserv.

I am not currently at home to inspect the original files for the government quests.

**Comment by fuzziqersoftware** [comment]
I believe the server ignores the internal numbers entirely at this point and instead orders quests based on the number in the filename. So to reorder quests within a category, simply change the number in the filename.

The following have all been fixed:
* The Japanese versions of the joinable government quests did not have the joinable flag set in their headers, so the server considered them to be different quests. I've updated the headers on all of these files.
* Lost HELL PALLASCH has been renumbered to q061.
* Ephinea has Rappy's Holiday and Gallon's Treachery in Retrieval as well, which to me confirms where they should be, so I've moved them to that category.
* I've added a condition to q124 to make it only appear when there is one player present in the game. I think this should suffice; I'm not going to create a separate category that causes the quest to only appear in One Person mode games.
