### ISSUE TITLE
[DC V2] $savechar error

### ISSUE THREAD

**Issue by Sifl46** [fuzziqersoftware/newserv#498]
Hello.
I have been having trouble using the $savechar command via DCv2 US.
I am being given an error along the lines of "Failed: unordered_map::at: key not found" In the game. Unfortunately the server console doesn't really have anything else to say about it, minus logging the sent and received packets.

I originally tried this on my Debian host. Then tried it again on my local computer (MacOS) for good measure. Both give me the same result.
This is with the latest commit at the time of writing.

FWIW, here's the packet log via the server:

> I 41578 2024-05-16 14:00:19 - [Commands] Received from C-2 (Bnuyy) @ ipv4:192.168.64.98:1794 (version=DC_V2 command=06 flag=00)
> 0000 | 06 00 1C 00 00 00 00 00 00 00 00 00 09 45 24 73 |              E$s
> 0010 | 61 76 65 63 68 61 72 20 31 00 00 00             | avechar 1       
> I 41578 2024-05-16 14:00:19 - [Commands] Sending to C-2 (Bnuyy) @ ipv4:192.168.64.98:1794 (version=DC_V2 command=B0 flag=00)
> 0000 | B0 00 38 00 00 00 00 00 00 00 00 00 09 43 36 46 |   8          C6F
> 0010 | 61 69 6C 65 64 3A 0A 75 6E 6F 72 64 65 72 65 64 | ailed: unordered
> 0020 | 5F 6D 61 70 3A 3A 61 74 3A 20 6B 65 79 20 6E 6F | _map::at: key no
> 0030 | 74 20 66 6F 75 6E 64 00                         | t found  
> 

If there's any more information I can give, do let me know.

**Comment by fuzziqersoftware** [comment]
This might be because the GetExtendedPlayerInfo patch is missing or failed to compile. Search for GetExtendedPlayerInfo in the messages that the server produces when you start it up. You should see something like this:
```
I 94884 2024-05-16 19:58:21 - [FunctionCompiler] Compiled function [00000076/324F4546] GetExtendedPlayerInfo.2OEF (SH-4)
I 94884 2024-05-16 19:58:21 - [FunctionCompiler] Compiled function [00000077/324F4A35] GetExtendedPlayerInfo.2OJ5 (SH-4)
I 94884 2024-05-16 19:58:21 - [FunctionCompiler] Compiled function [00000078/324F4A46] GetExtendedPlayerInfo.2OJF (SH-4)
I 94884 2024-05-16 19:58:21 - [FunctionCompiler] Compiled function [00000079/324F5046] GetExtendedPlayerInfo.2OPF (SH-4)
```

If you instead see messages like "Failed to compile function GetExtendedPlayerInfo", that would indicate what the problem is. Note that these patches might depend on some bugfixes introduced in recent commits to resource_dasm, so if you haven't updated resource_dasm in a while, that could be the cause of any "Failed to compile function" errors.

**Comment by Sifl46** [comment]
It would appear I had missed the step to "make install" resource_dasm. After updating all my repos and reconpiling for good measure. $savechar is now functional. Thank you for your help. My childhood dreamcast characters are now transferred to GC, as well as backed up :)
