### ISSUE TITLE
Cannot Start due to "Tablet" parsing.

### ISSUE THREAD

**Issue by Xlaits** [fuzziqersoftware/newserv#509]
**Describe the bug**
As it says in the title, I am not sure how to make it any clearer.
Server refuses to start with the error `Top-level exception (runtime_error): cannot parse item description "Tablet" (as text: item not found: tablet) (as data: data is too short)`

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Start server.

**Game version(s) (choose one or more of the following):**
BB

**Server log output**
[server-log.txt](https://github.com/user-attachments/files/15506425/server-log.txt)

**Additional context**
Stackdump file created by the program, mentioned at the end of the log.
[newserv-windows.exe.stackdump.zip](https://github.com/user-attachments/files/15506430/newserv-windows.exe.stackdump.zip)

**Comment by fuzziqersoftware** [comment]
Which BB client are you using? It's likely that your client doesn't have the Tablet item at all; some of the older clients don't have it. Since the server uses the client's item definitions, it doesn't exist on the server either. To work around this, you can look for `"Tablet"` (with quotes) in config.json and just delete it; there should be 3 matches.

**Comment by Xlaits** [comment]
I think it may be an old Teth client, based on the included exe editor.

**Comment by Matt-Swift** [comment]
It looks like newserv is loading unitxt_e.prs from the data.gsl file and referencing that for the English strings in the configuration file, and the unitxt files in data.gsl are outdated release files, in which Tablet did not exist (but it definitely exists in the up-to-date unitxt_j.prs file that Teth provides in the data folder itself).

The Teth client is Japanese and uses unitxt_j.prs, but this isn't being used for the English strings by newserv. Following the above advice will just have it constantly error on each Japanese-exclusive item that was never added to the English release.

If you rename unitxt_j.prs to unitxt_e.prs, it also errors because there is a typo where "Revival Cuirass" is named "Revival Curiass", so it errors on that.

As a fast workaround, put the files in this archive: [unitxt.zip](https://github.com/user-attachments/files/15510689/unitxt.zip) into your patch-bb folder and it will boot the server.

**Comment by Xlaits** [comment]
That did indeed fix the issue! Now I have a completely separate problem that I must figure out, as it thinks my server is full.

**Comment by Matt-Swift** [comment]
You didn't change your local address from `en0` in config.json looking at the server log, you need to change that to your local IP address (127.0.0.1 if running server on same PC you're playing it, 192.168.56.1 if not)

**Comment by Xlaits** [comment]
That would explain it. I would make mention of this in the config.example.json

**Comment by Xlaits** [comment]
I may also have other users joining remotely, so I don't know if that would effect anything.

**Comment by Xlaits** [comment]
> You didn't change your local address from `en0` in config.json looking at the server log, you need to change that to your local IP address (127.0.0.1 if running server on same PC you're playing it, 192.168.56.1 if not)

This doesn't seem to have actually made a difference. The client I am using is actually using the public facing IP to connect.

**Comment by Xlaits** [comment]
No, that is indeed the correct IP for this PC. My network structure is 192.168.0.* addresses.

**Comment by Xlaits** [comment]
Okay, so I think I might not have all the ports required opened, and my router is incredibly dumb, not allowing me to define ranges or lists. Give me a moment.
