### ISSUE TITLE
 backreference offset beyond beginning of output

### ISSUE THREAD

**Issue by ZikZakFR** [fuzziqersoftware/newserv#51]
Using a Gamecube version, I allow unregistered user for local tests.
I can connect to the server but as soon as I start or download a quest I get either a segfault of newserv or this message in the console:

W 252364 2022-12-10 11:07:39 - [Server] Error processing client command: backreference offset beyond beginning of output
I 252364 2022-12-10 11:07:39 - [Server] Client disconnected: C-1 on fd 35

Do I have to do something with the quest files inside "system"?

**Comment by fuzziqersoftware** [comment]
I'm guessing this is due to an unsafe memory access somewhere deep in compression or decompression code. A few questions:
- What kind of environment are you running newserv in? (macOS, Linux, Raspbian, ...?)
- Does this happen with all quests, or specific quests?
- Can you get a stacktrace? (Run newserv with gdb or lldb, then run `bt` when it crashes)

**Comment by fuzziqersoftware** [comment]
I pushed a change just now that may fix the issue. Please try it out and let me know if it still doesn't work.

**Comment by ZikZakFR** [comment]
I run newserv on archlinux
It happens with the few quest I tried, and picked randomly. The result is the same downloading the quest from a lobby or registering it from the frontdesk of a ship.
I run the game from a gcloader, the game is the PAL version.

Note that some times the server SegFault or stays up, in any case the user is disconnected.
I get disconnected from the server after the quest is downloaded. It seems that when the quest should be started is when I'm kicked.

Can you give the full commands for you last point (stacktrace)?

**Comment by ZikZakFR** [comment]
> I pushed a change just now that may fix the issue. Please try it out and let me know if it still doesn't work.

Okay I'll pull the changes and recompile the server.

**Comment by ZikZakFR** [comment]
Almost there :)
Downloading the quest to memory card worked.
Then I created a team and registered to the (very same) quest from the front desk and it killed the server with a segmentation fault.

**Comment by fuzziqersoftware** [comment]
Yeah, this turned out to be three separate bugs:
- prs_decompress_size didn't correctly skip a byte from the input for literal commands (this was the first fix above)
- The quest barrier (AC) command handler didn't check for missing clients (this is what caused the segfaults)
- Sometimes quest data was sent too quickly to GC clients, which could cause them to crash
I've pushed another fix just now which addresses the second and third issues. Let me know if this doesn't fix it.

**Comment by ZikZakFR** [comment]
Downloading a quest to the memory card works.
Running and completing a quest from the ship mission desk works too.
