### ISSUE TITLE
[Blue Burst] Desynced Items stuck on the ground got Error.100 after attempting to pickup several times

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#534]
**Describe the bug**
This happened while I was doing a VH one-person mode run in the MInes 1 area, in the final room before i got disconnected the enemies dropped 1 stack of ~150 meseta and 1 monomate, i tried to pick them up while I was still killing the monsters in the room, seeing the items still being stuck on the ground i quickly teleported back to P2 and returned, attempted to pick them up again and they were still stuck on the ground then shortly after I got an Error.100.

The only thing in the console that mentions something related to an error is an entry that says `[C-4F] Idle timeout expired` towards the end of the log, I'm attaching the log of the whole session before the Error.100 but I cannot find anything that is related to an error anywhere

**Game version(s) (choose one or more of the following):**
BB

**Server log output**
[DesyncMesetaMono2.txt](https://github.com/user-attachments/files/16091374/DesyncMesetaMono2.txt)

**Comment by fuzziqersoftware** [comment]
"Idle timeout expired" happens when your client stops sending data. Specifically, your client did not respond to `10 00 1D 00 00 00 00 00 00 06 1C 5F 42 A9 A3 1E` within 30 seconds, so the server disconnected you. This doesn't appear to be a server-side issue; it's more likely to have been a network issue on your end.
