### ISSUE TITLE
W 1289 2024-07-12 06:34:05 - I/O error reading from terminal: io error on fd 0: cannot read from stream (-1)

### ISSUE THREAD

**Issue by Kfalt** [fuzziqersoftware/newserv#540]
W 1289 2024-07-12 06:34:05 - I/O error reading from terminal: io error on fd 0: cannot read from stream (-1)

**Comment by ShiftaDeband** [comment]
Can you provide more information about the issue via the template provided?

More context would be a huge help.

> **Describe the bug**
> Write a clear and concise description of what the bug is, and what you expected to happen instead.
> 
> **To reproduce**
> Fill in steps to reproduce the behavior, such as:
> 1. Connect to server
> 2. Create a game
> 3. Start quest X
> 4. Talk to NPC Y
> 
> **Game version(s) (choose one or more of the following):**
> DC NTE, DC prototype, DC v1, DC v2, PC, GC Ep1&2, GC Ep3, Xbox, BB
> 
> **Server log output**
> On macOS/Linux, or in a Cygwin shell on Windows, you can run the server as `./newserv 2>&1 | tee server-log.txt` to generate a log file. Do that, then do whatever you need to do to get the bug to happen, then upload the log file here.
> 
> **Additional context**
> Add any other context about the problem here.
>

**Comment by fuzziqersoftware** [comment]
This is a Windows-specific issue due to a bug in Cygwin, and it doesn't appear to be harmful; it only occurs when the window size is changed and it doesn't seem to break anything. Fixing this would require a fairly unpleasant workaround, so I'm deciding that it's not worth the time to fix since it only occurs in fairly-rare scenarios.
