### ISSUE TITLE
Client Disconnects when killing BEE's

### ISSUE THREAD

**Issue by Shade53** [fuzziqersoftware/newserv#554]
**Describe the bug**
When killing a Chaos Sorcerer in Normal-Very Hard difficulties the player will be disconnected with a 100 error: "Check Cable" every time.

**To reproduce**
Steps to reproduce:
1. Connect to server
2. Create a game with Normal, Hard or Very Hard difficulty
3. Go to the Ruins
4. Kill a Chaos Sorcerer

**Game version(s) (choose one or more of the following):**
BB

**Server log output**
[server-log.txt](https://github.com/user-attachments/files/16632543/server-log.txt)

Based on the data from the logs I've captured both here and from other times it looks like the client is disconnected because either the game or server is expecting a drop table entry for "BEE_R" or "BEE_L", those lil crystals, it seems.

**Additional context**
This problem was not seen back before the commit that added in material count resetting, so I imagine that one of the commits from that one on was when this issue was introduced.

**Comment by fuzziqersoftware** [comment]
You don't have the map_*.dat files from your BB client in the system/patch-bb/data/ directory. These files are required because the server uses them to generate the same enemy lists as the client when a game is created, and issues like this happen when the map files aren't the same so the enemy lists go out of sync.

Make sure you have all the required files in system/patch-bb/, as specified in the readme. If the problem persists after fixing that, you can reopen this issue.

**Comment by Shade53** [comment]
Darn, I was hoping that I could allow more map texture customization between different player's clients, but if it's necessary to have all map files synced between server and client then that's how it's going to have to be.

Thanks for all the awesome help!
