### ISSUE TITLE
[Episode 3] Unable to play any monster cards in certain scenarios

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#97]
Note: The Episode 3 Plus Mod card definitions were loaded during this.

During a 4-player match online, Ohgun was unable to play any monster cards on the Dolor Odor map. The monster cards tried were Govulmer, Merlan, and Hildebear.

I originally tried to place a Hildebear on the opposite side of the map which didn't work, but then nothing worked anywhere.

I'm not sure if I grabbed the correct logs, see below, I can get more if needed.

[Ohgun.txt](https://github.com/fuzziqersoftware/newserv/files/12506445/Ohgun.txt)

**Comment by fuzziqersoftware** [comment]
This is fixed now. The issue was that we incorrectly computed the creature summoning area for maps that are oriented left-right internally. The area in which you're allowed to summon creatures is based on the direction you're facing when the battle begins; most maps have the players start at the top and bottom, but Dolor Odor has them starting at the left and right edges instead.
