### ISSUE TITLE
[Episode 3] Wii client hangs after redraw choice at start of game

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#98]
Note: The Episode 3 Plus mod card definitions were loaded for all of this.

I don't have any logs for this, but will attempt to repro it later, this is mostly just to leave myself a reminder and somewhere to post them (ping me if I haven't gotten the logs after a while).

In a session with 3 Dolphin clients and 1 Wii client, the Wii client was always kicked from the game after the choice to redraw, no matter which option was chosen. This caused the game to infinitely hang as the player never moves or is replaced by COM.

The Wii player suspects it may be something to do with the saving speed of a memory card vs a digital one as part of Dolphin, and also wants to test a faster memory card on the Wii to see if that resolves the issue.

**Comment by fuzziqersoftware** [comment]
I've looked at the logs here, and there isn't anything obvious going on here that catches my eye. The behavior definitely looks like packet loss of some kind, either somewhere between the server and client or on the client side. I'm inclined to believe it's a Nintendont issue as well, especially since others have had trouble on Wiis, but feel free to upload more info/logs here when it happen again and I'll take a look at those too.
